@file:Suppress("warnings")

/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.chat.tables.references

import net.barrage.llmao.chat.tables.AgentCollections
import net.barrage.llmao.chat.tables.AgentConfigurations
import net.barrage.llmao.chat.tables.AgentPermissions
import net.barrage.llmao.chat.tables.AgentTools
import net.barrage.llmao.chat.tables.Agents
import net.barrage.llmao.chat.tables.Chats
import net.barrage.llmao.chat.tables.WhatsAppNumbers

/** The table <code>public.agent_collections</code>. */
val AGENT_COLLECTIONS: AgentCollections = AgentCollections.AGENT_COLLECTIONS

/** The table <code>public.agent_configurations</code>. */
val AGENT_CONFIGURATIONS: AgentConfigurations = AgentConfigurations.AGENT_CONFIGURATIONS

/** The table <code>public.agent_permissions</code>. */
val AGENT_PERMISSIONS: AgentPermissions = AgentPermissions.AGENT_PERMISSIONS

/** The table <code>public.agent_tools</code>. */
val AGENT_TOOLS: AgentTools = AgentTools.AGENT_TOOLS

/** The table <code>public.agents</code>. */
val AGENTS: Agents = Agents.AGENTS

/** The table <code>public.chats</code>. */
val CHATS: Chats = Chats.CHATS

/** The table <code>public.whats_app_numbers</code>. */
val WHATS_APP_NUMBERS: WhatsAppNumbers = WhatsAppNumbers.WHATS_APP_NUMBERS
