@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.core.indexes


import net.barrage.llmao.core.tables.ApplicationSettings
import net.barrage.llmao.core.tables.MessageAttachments
import net.barrage.llmao.core.tables.MessageGroupEvaluations
import net.barrage.llmao.core.tables.MessageGroups
import net.barrage.llmao.core.tables.Messages
import net.barrage.llmao.core.tables.TokenUsage

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val APPLICATION_SETTINGS_NAME_IDX: Index = Internal.createIndex(DSL.name("application_settings_name_idx"), ApplicationSettings.APPLICATION_SETTINGS, arrayOf(ApplicationSettings.APPLICATION_SETTINGS.NAME), false)
val MESSAGE_ATTACHMENTS_MESSAGE_ID_IDX: Index = Internal.createIndex(DSL.name("message_attachments_message_id_idx"), MessageAttachments.MESSAGE_ATTACHMENTS, arrayOf(MessageAttachments.MESSAGE_ATTACHMENTS.MESSAGE_ID), false)
val MESSAGE_GROUP_EVALUATIONS_EVALUATION_IDX: Index = Internal.createIndex(DSL.name("message_group_evaluations_evaluation_idx"), MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS, arrayOf(MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS.EVALUATION), false)
val MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_IDX: Index = Internal.createIndex(DSL.name("message_group_evaluations_message_group_id_idx"), MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS, arrayOf(MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS.MESSAGE_GROUP_ID), false)
val MESSAGE_GROUPS_PARENT_ID_IDX: Index = Internal.createIndex(DSL.name("message_groups_parent_id_idx"), MessageGroups.MESSAGE_GROUPS, arrayOf(MessageGroups.MESSAGE_GROUPS.PARENT_ID), false)
val MESSAGES_MESSAGE_GROUP_ID_IDX: Index = Internal.createIndex(DSL.name("messages_message_group_id_idx"), Messages.MESSAGES, arrayOf(Messages.MESSAGES.MESSAGE_GROUP_ID), false)
val TOKEN_USAGE_MODEL_IDX: Index = Internal.createIndex(DSL.name("token_usage_model_idx"), TokenUsage.TOKEN_USAGE, arrayOf(TokenUsage.TOKEN_USAGE.MODEL), false)
val TOKEN_USAGE_PROVIDER_IDX: Index = Internal.createIndex(DSL.name("token_usage_provider_idx"), TokenUsage.TOKEN_USAGE, arrayOf(TokenUsage.TOKEN_USAGE.PROVIDER), false)
val TOKEN_USAGE_USAGE_TYPE_IDX: Index = Internal.createIndex(DSL.name("token_usage_usage_type_idx"), TokenUsage.TOKEN_USAGE, arrayOf(TokenUsage.TOKEN_USAGE.USAGE_TYPE), false)
val TOKEN_USAGE_USER_ID_IDX: Index = Internal.createIndex(DSL.name("token_usage_user_id_idx"), TokenUsage.TOKEN_USAGE, arrayOf(TokenUsage.TOKEN_USAGE.USER_ID), false)
val TOKEN_USAGE_WORKFLOW_ID_IDX: Index = Internal.createIndex(DSL.name("token_usage_workflow_id_idx"), TokenUsage.TOKEN_USAGE, arrayOf(TokenUsage.TOKEN_USAGE.WORKFLOW_ID), false)
val TOKEN_USAGE_WORKFLOW_TYPE_IDX: Index = Internal.createIndex(DSL.name("token_usage_workflow_type_idx"), TokenUsage.TOKEN_USAGE, arrayOf(TokenUsage.TOKEN_USAGE.WORKFLOW_TYPE), false)
