@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.bonvoyage.tables.references


import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelExpenses
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelManagerUserMappings
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelManagers
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelRequests
import net.barrage.llmao.bonvoyage.tables.BonvoyageTripWelcomeMessages
import net.barrage.llmao.bonvoyage.tables.BonvoyageTrips



/**
 * The table <code>public.bonvoyage_travel_expenses</code>.
 */
val BONVOYAGE_TRAVEL_EXPENSES: BonvoyageTravelExpenses = BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES

/**
 * The table <code>public.bonvoyage_travel_manager_user_mappings</code>.
 */
val BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS: BonvoyageTravelManagerUserMappings = BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS

/**
 * The table <code>public.bonvoyage_travel_managers</code>.
 */
val BONVOYAGE_TRAVEL_MANAGERS: BonvoyageTravelManagers = BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS

/**
 * The table <code>public.bonvoyage_travel_requests</code>.
 */
val BONVOYAGE_TRAVEL_REQUESTS: BonvoyageTravelRequests = BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS

/**
 * The table <code>public.bonvoyage_trip_welcome_messages</code>.
 */
val BONVOYAGE_TRIP_WELCOME_MESSAGES: BonvoyageTripWelcomeMessages = BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES

/**
 * The table <code>public.bonvoyage_trips</code>.
 */
val BONVOYAGE_TRIPS: BonvoyageTrips = BonvoyageTrips.BONVOYAGE_TRIPS
