include:
  - project: devops/ci-template
    ref: v1.1.0
    file: GitlabFlow/Deploy-custom.yml

variables:
    HELM_RELEASE_PREFIX: llmao-kappi

build-and-test:
  stage: build
  image:
    name: nexus.barrage.net:13455/barrage-internal/ubuntu-java-17-dind
  tags:
    - docker-executor
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    TESTCONTAINERS_STARTUP_TIMEOUT: "120"
    TESTCONTAINERS_RYUK_DISABLED: "true"
  services:
    - name: docker:dind-rootless
      alias: docker
  script:
    - screen -d -m /usr/local/bin/dockerd
    - cp gradle.example.properties gradle.properties
    - ./gradlew test
    - ./gradlew buildFatJar
  artifacts:
    paths:
      - build/libs/

containerize:
  stage: build
  needs:
    - build-and-test
  extends: .build
  rules:
    - !reference [ .build, rules ]
    - when: on_success

review:
  extends: .review_app
  needs:
    - containerize
  variables:
    KUBE_INGRESS_BASE_DOMAIN: barrage.dev
  environment:
    on_stop: cleanup
  rules:
    - !reference [ ".review_app", "rules" ]
    - when: on_success

cleanup:
  extends: .stop_review
  rules:
    - !reference [ ".stop_review", "rules" ]
    - when: manual

deploy dev:
  extends: .development
  variables:
    KUBE_INGRESS_BASE_DOMAIN: barrage.dev
  needs:
    - containerize
  rules:
    - !reference [ .development, rules ]
    - when: on_success
