include:
  - project: devops/ci-template
    ref: v1.0.0
    file: GitlabFlow/Deploy-custom.yml

build-and-test:
  stage: build
  image:
    name: nexus.barrage.net:13455/barrage-internal/ubuntu-java-17
  tags:
    - docker-executor
  variables:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: kappi
  #    PGPORT: 5454
  services:
    - name: postgres:latest
      alias: postgres
    - name: semitechnologies/weaviate:1.20.0
      alias: weaviate
      variables:
        QUERY_DEFAULTS_LIMIT: "25"
        AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
        PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
        DEFAULT_VECTORIZER_MODULE: "none"
        ENABLE_MODULES: ""
        CLUSTER_HOSTNAME: "node1"
      command: [ "/bin/bash", "-c", "--host 0.0.0.0 --port 8080 --scheme http && weaviate" ]
  script:
    - cp config/application.example.yaml config/application.yaml
    - sed -i "s|jdbc:postgresql://localhost:5454/kappi|jdbc:postgresql://postgres:5432/kappi|g" config/application.yaml
    - cat config/application.yaml
    - cp gradle.example.properties gradle.properties
    - sed -i "s|jdbc:postgresql://localhost:5454/kappi|jdbc:postgresql://postgres:5432/kappi|g" gradle.properties
    - cat gradle.properties
    - ./gradlew test
    #    - mkdir build/libs/
    - ./gradlew buildFatJar
  artifacts:
    paths:
      - build/libs/

containerize:
  stage: build
  needs:
    - build-and-test
  extends: .build
  rules:
    - !reference [.build, rules]
    - when: on_success

review:
  extends: .review_app_staging
  needs:
    - containerize
  variables:
    HELM_RELEASE_NAME: kappi
  environment:
    on_stop: cleanup
  rules:
    - !reference [ '.review_app', 'rules' ]
    - when: on_success

cleanup:
  extends: .stop_review_staging
  variables:
    HELM_RELEASE_NAME: kubetest
  rules:
    - !reference [ '.stop_review', 'rules' ]
    - when: manual

deploy stg:
  extends: .pre-production
  variables:
    HELM_RELEASE_NAME: kappi
  needs:
    - containerize
  rules:
    - !reference [ .development, rules ]
    - when: on_success
