services:
  postgres:
    image: postgres:latest
    ports:
      - '5454:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kappi
    volumes:
      - ~/docker-data/postgres-kappi:/var/lib/postgresql/data
