/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.chat.tables

import java.time.OffsetDateTime
import java.util.UUID
import kotlin.collections.Collection
import kotlin.collections.List
import net.barrage.llmao.chat.Public
import net.barrage.llmao.chat.indexes.AGENT_COLLECTIONS_AGENT_ID_IDX
import net.barrage.llmao.chat.keys.AGENT_COLLECTIONS_PKEY
import net.barrage.llmao.chat.keys.AGENT_COLLECTIONS_UNIQUE_AGENT_COLLECTION
import net.barrage.llmao.chat.keys.AGENT_COLLECTIONS__AGENT_COLLECTIONS_AGENT_ID_FKEY
import net.barrage.llmao.chat.tables.Agents.AgentsPath
import net.barrage.llmao.chat.tables.records.AgentCollectionsRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/** This class is generated by jOOQ. */
@Suppress("warnings")
open class AgentCollections(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, AgentCollectionsRecord>?,
  parentPath: InverseForeignKey<out Record, AgentCollectionsRecord>?,
  aliased: Table<AgentCollectionsRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?,
) :
  TableImpl<AgentCollectionsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
  ) {
  companion object {

    /** The reference instance of <code>public.agent_collections</code> */
    val AGENT_COLLECTIONS: AgentCollections = AgentCollections()
  }

  /** The class holding records for this type */
  override fun getRecordType(): Class<AgentCollectionsRecord> = AgentCollectionsRecord::class.java

  /** The column <code>public.agent_collections.id</code>. */
  val ID: TableField<AgentCollectionsRecord, UUID?> =
    createField(
      DSL.name("id"),
      SQLDataType.UUID.nullable(false)
        .defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)),
      this,
      "",
    )

  /** The column <code>public.agent_collections.agent_id</code>. */
  val AGENT_ID: TableField<AgentCollectionsRecord, UUID?> =
    createField(DSL.name("agent_id"), SQLDataType.UUID.nullable(false), this, "")

  /** The column <code>public.agent_collections.instruction</code>. */
  val INSTRUCTION: TableField<AgentCollectionsRecord, String?> =
    createField(DSL.name("instruction"), SQLDataType.CLOB.nullable(false), this, "")

  /** The column <code>public.agent_collections.collection</code>. */
  val COLLECTION: TableField<AgentCollectionsRecord, String?> =
    createField(DSL.name("collection"), SQLDataType.CLOB.nullable(false), this, "")

  /** The column <code>public.agent_collections.amount</code>. */
  val AMOUNT: TableField<AgentCollectionsRecord, Int?> =
    createField(DSL.name("amount"), SQLDataType.INTEGER.nullable(false), this, "")

  /** The column <code>public.agent_collections.max_distance</code>. */
  val MAX_DISTANCE: TableField<AgentCollectionsRecord, Double?> =
    createField(DSL.name("max_distance"), SQLDataType.DOUBLE, this, "")

  /** The column <code>public.agent_collections.embedding_model</code>. */
  val EMBEDDING_MODEL: TableField<AgentCollectionsRecord, String?> =
    createField(DSL.name("embedding_model"), SQLDataType.CLOB.nullable(false), this, "")

  /** The column <code>public.agent_collections.embedding_provider</code>. */
  val EMBEDDING_PROVIDER: TableField<AgentCollectionsRecord, String?> =
    createField(DSL.name("embedding_provider"), SQLDataType.CLOB.nullable(false), this, "")

  /** The column <code>public.agent_collections.vector_provider</code>. */
  val VECTOR_PROVIDER: TableField<AgentCollectionsRecord, String?> =
    createField(DSL.name("vector_provider"), SQLDataType.CLOB.nullable(false), this, "")

  /** The column <code>public.agent_collections.created_at</code>. */
  val CREATED_AT: TableField<AgentCollectionsRecord, OffsetDateTime?> =
    createField(
      DSL.name("created_at"),
      SQLDataType.TIMESTAMPWITHTIMEZONE(6)
        .nullable(false)
        .defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
      this,
      "",
    )

  /** The column <code>public.agent_collections.updated_at</code>. */
  val UPDATED_AT: TableField<AgentCollectionsRecord, OffsetDateTime?> =
    createField(
      DSL.name("updated_at"),
      SQLDataType.TIMESTAMPWITHTIMEZONE(6)
        .nullable(false)
        .defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
      this,
      "",
    )

  private constructor(
    alias: Name,
    aliased: Table<AgentCollectionsRecord>?,
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<AgentCollectionsRecord>?,
    parameters: Array<Field<*>?>?,
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<AgentCollectionsRecord>?,
    where: Condition?,
  ) : this(alias, null, null, null, aliased, null, where)

  /** Create an aliased <code>public.agent_collections</code> table reference */
  constructor(alias: String) : this(DSL.name(alias))

  /** Create an aliased <code>public.agent_collections</code> table reference */
  constructor(alias: Name) : this(alias, null)

  /** Create a <code>public.agent_collections</code> table reference */
  constructor() : this(DSL.name("agent_collections"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, AgentCollectionsRecord>?,
    parentPath: InverseForeignKey<out Record, AgentCollectionsRecord>?,
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    AGENT_COLLECTIONS,
    null,
    null,
  )

  /** A subtype implementing {@link Path} for simplified path-based joins. */
  open class AgentCollectionsPath : AgentCollections, Path<AgentCollectionsRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, AgentCollectionsRecord>?,
      parentPath: InverseForeignKey<out Record, AgentCollectionsRecord>?,
    ) : super(path, childPath, parentPath)

    private constructor(alias: Name, aliased: Table<AgentCollectionsRecord>) : super(alias, aliased)

    override fun `as`(alias: String): AgentCollectionsPath =
      AgentCollectionsPath(DSL.name(alias), this)

    override fun `as`(alias: Name): AgentCollectionsPath = AgentCollectionsPath(alias, this)

    override fun `as`(alias: Table<*>): AgentCollectionsPath =
      AgentCollectionsPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC

  override fun getIndexes(): List<Index> = listOf(AGENT_COLLECTIONS_AGENT_ID_IDX)

  override fun getPrimaryKey(): UniqueKey<AgentCollectionsRecord> = AGENT_COLLECTIONS_PKEY

  override fun getUniqueKeys(): List<UniqueKey<AgentCollectionsRecord>> =
    listOf(AGENT_COLLECTIONS_UNIQUE_AGENT_COLLECTION)

  override fun getReferences(): List<ForeignKey<AgentCollectionsRecord, *>> =
    listOf(AGENT_COLLECTIONS__AGENT_COLLECTIONS_AGENT_ID_FKEY)

  /** Get the implicit join path to the <code>public.agents</code> table. */
  fun agents(): AgentsPath = agents

  val agents: AgentsPath by lazy {
    AgentsPath(this, AGENT_COLLECTIONS__AGENT_COLLECTIONS_AGENT_ID_FKEY, null)
  }

  override fun `as`(alias: String): AgentCollections = AgentCollections(DSL.name(alias), this)

  override fun `as`(alias: Name): AgentCollections = AgentCollections(alias, this)

  override fun `as`(alias: Table<*>): AgentCollections = AgentCollections(alias.qualifiedName, this)

  /** Rename this table */
  override fun rename(name: String): AgentCollections = AgentCollections(DSL.name(name), null)

  /** Rename this table */
  override fun rename(name: Name): AgentCollections = AgentCollections(name, null)

  /** Rename this table */
  override fun rename(name: Table<*>): AgentCollections = AgentCollections(name.qualifiedName, null)

  /** Create an inline derived table from this table */
  override fun where(condition: Condition?): AgentCollections =
    AgentCollections(qualifiedName, if (aliased()) this else null, condition)

  /** Create an inline derived table from this table */
  override fun where(conditions: Collection<Condition>): AgentCollections =
    where(DSL.and(conditions))

  /** Create an inline derived table from this table */
  override fun where(vararg conditions: Condition?): AgentCollections = where(DSL.and(*conditions))

  /** Create an inline derived table from this table */
  override fun where(condition: Field<Boolean?>?): AgentCollections =
    where(DSL.condition(condition))

  /** Create an inline derived table from this table */
  @PlainSQL override fun where(condition: SQL): AgentCollections = where(DSL.condition(condition))

  /** Create an inline derived table from this table */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): AgentCollections =
    where(DSL.condition(condition))

  /** Create an inline derived table from this table */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AgentCollections =
    where(DSL.condition(condition, *binds))

  /** Create an inline derived table from this table */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AgentCollections =
    where(DSL.condition(condition, *parts))

  /** Create an inline derived table from this table */
  override fun whereExists(select: Select<*>): AgentCollections = where(DSL.exists(select))

  /** Create an inline derived table from this table */
  override fun whereNotExists(select: Select<*>): AgentCollections = where(DSL.notExists(select))
}
