/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.chat.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import net.barrage.llmao.chat.Public
import net.barrage.llmao.chat.indexes.AGENT_PERMISSIONS_AGENT_ID_IDX
import net.barrage.llmao.chat.keys.AGENT_GROUPS_UNIQUE_AGENT_GROUP
import net.barrage.llmao.chat.keys.AGENT_PERMISSIONS_PKEY
import net.barrage.llmao.chat.keys.AGENT_PERMISSIONS__AGENT_PERMISSIONS_AGENT_ID_FKEY
import net.barrage.llmao.chat.tables.Agents.AgentsPath
import net.barrage.llmao.chat.tables.records.AgentPermissionsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AgentPermissions(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AgentPermissionsRecord>?,
    parentPath: InverseForeignKey<out Record, AgentPermissionsRecord>?,
    aliased: Table<AgentPermissionsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AgentPermissionsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.agent_permissions</code>
         */
        val AGENT_PERMISSIONS: AgentPermissions = AgentPermissions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AgentPermissionsRecord> = AgentPermissionsRecord::class.java

    /**
     * The column <code>public.agent_permissions.id</code>.
     */
    val ID: TableField<AgentPermissionsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.agent_permissions.agent_id</code>.
     */
    val AGENT_ID: TableField<AgentPermissionsRecord, UUID?> = createField(DSL.name("agent_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.agent_permissions.group</code>.
     */
    val GROUP: TableField<AgentPermissionsRecord, String?> = createField(DSL.name("group"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.agent_permissions.created_by</code>.
     */
    val CREATED_BY: TableField<AgentPermissionsRecord, String?> = createField(DSL.name("created_by"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.agent_permissions.created_at</code>.
     */
    val CREATED_AT: TableField<AgentPermissionsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<AgentPermissionsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AgentPermissionsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AgentPermissionsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.agent_permissions</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.agent_permissions</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.agent_permissions</code> table reference
     */
    constructor(): this(DSL.name("agent_permissions"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AgentPermissionsRecord>?, parentPath: InverseForeignKey<out Record, AgentPermissionsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, AGENT_PERMISSIONS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AgentPermissionsPath : AgentPermissions, Path<AgentPermissionsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AgentPermissionsRecord>?, parentPath: InverseForeignKey<out Record, AgentPermissionsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AgentPermissionsRecord>): super(alias, aliased)
        override fun `as`(alias: String): AgentPermissionsPath = AgentPermissionsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AgentPermissionsPath = AgentPermissionsPath(alias, this)
        override fun `as`(alias: Table<*>): AgentPermissionsPath = AgentPermissionsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(AGENT_PERMISSIONS_AGENT_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<AgentPermissionsRecord> = AGENT_PERMISSIONS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<AgentPermissionsRecord>> = listOf(AGENT_GROUPS_UNIQUE_AGENT_GROUP)
    override fun getReferences(): List<ForeignKey<AgentPermissionsRecord, *>> = listOf(AGENT_PERMISSIONS__AGENT_PERMISSIONS_AGENT_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.agents</code> table.
     */
    fun agents(): AgentsPath = agents
    val agents: AgentsPath by lazy { AgentsPath(this, AGENT_PERMISSIONS__AGENT_PERMISSIONS_AGENT_ID_FKEY, null) }
    override fun `as`(alias: String): AgentPermissions = AgentPermissions(DSL.name(alias), this)
    override fun `as`(alias: Name): AgentPermissions = AgentPermissions(alias, this)
    override fun `as`(alias: Table<*>): AgentPermissions = AgentPermissions(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AgentPermissions = AgentPermissions(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AgentPermissions = AgentPermissions(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AgentPermissions = AgentPermissions(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AgentPermissions = AgentPermissions(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AgentPermissions = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AgentPermissions = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AgentPermissions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AgentPermissions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AgentPermissions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AgentPermissions = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AgentPermissions = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AgentPermissions = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AgentPermissions = where(DSL.notExists(select))
}
