/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.chat.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import net.barrage.llmao.chat.Public
import net.barrage.llmao.chat.indexes.AGENT_CONFIGURATIONS_AGENT_ID_IDX
import net.barrage.llmao.chat.keys.AGENT_CONFIGURATIONS_PKEY
import net.barrage.llmao.chat.keys.AGENT_CONFIGURATIONS__AGENT_CONFIGURATIONS_AGENT_ID_FKEY
import net.barrage.llmao.chat.keys.CHATS__CHATS_AGENT_CONFIGURATION_ID_FKEY
import net.barrage.llmao.chat.tables.Agents.AgentsPath
import net.barrage.llmao.chat.tables.Chats.ChatsPath
import net.barrage.llmao.chat.tables.records.AgentConfigurationsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AgentConfigurations(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AgentConfigurationsRecord>?,
    parentPath: InverseForeignKey<out Record, AgentConfigurationsRecord>?,
    aliased: Table<AgentConfigurationsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AgentConfigurationsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.agent_configurations</code>
         */
        val AGENT_CONFIGURATIONS: AgentConfigurations = AgentConfigurations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AgentConfigurationsRecord> = AgentConfigurationsRecord::class.java

    /**
     * The column <code>public.agent_configurations.id</code>.
     */
    val ID: TableField<AgentConfigurationsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.agent_configurations.agent_id</code>.
     */
    val AGENT_ID: TableField<AgentConfigurationsRecord, UUID?> = createField(DSL.name("agent_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.agent_configurations.version</code>.
     */
    val VERSION: TableField<AgentConfigurationsRecord, Int?> = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.agent_configurations.context</code>.
     */
    val CONTEXT: TableField<AgentConfigurationsRecord, String?> = createField(DSL.name("context"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.agent_configurations.llm_provider</code>.
     */
    val LLM_PROVIDER: TableField<AgentConfigurationsRecord, String?> = createField(DSL.name("llm_provider"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.agent_configurations.model</code>.
     */
    val MODEL: TableField<AgentConfigurationsRecord, String?> = createField(DSL.name("model"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.agent_configurations.presence_penalty</code>.
     */
    val PRESENCE_PENALTY: TableField<AgentConfigurationsRecord, Double?> = createField(DSL.name("presence_penalty"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>public.agent_configurations.max_history_tokens</code>.
     */
    val MAX_HISTORY_TOKENS: TableField<AgentConfigurationsRecord, Int?> = createField(DSL.name("max_history_tokens"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.agent_configurations.temperature</code>.
     */
    val TEMPERATURE: TableField<AgentConfigurationsRecord, Double?> = createField(DSL.name("temperature"), SQLDataType.DOUBLE.nullable(false).defaultValue(DSL.field(DSL.raw("0.1"), SQLDataType.DOUBLE)), this, "")

    /**
     * The column <code>public.agent_configurations.title_instruction</code>.
     */
    val TITLE_INSTRUCTION: TableField<AgentConfigurationsRecord, String?> = createField(DSL.name("title_instruction"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.agent_configurations.error_message</code>.
     */
    val ERROR_MESSAGE: TableField<AgentConfigurationsRecord, String?> = createField(DSL.name("error_message"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.agent_configurations.created_at</code>.
     */
    val CREATED_AT: TableField<AgentConfigurationsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.agent_configurations.updated_at</code>.
     */
    val UPDATED_AT: TableField<AgentConfigurationsRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<AgentConfigurationsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AgentConfigurationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AgentConfigurationsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.agent_configurations</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.agent_configurations</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.agent_configurations</code> table reference
     */
    constructor(): this(DSL.name("agent_configurations"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AgentConfigurationsRecord>?, parentPath: InverseForeignKey<out Record, AgentConfigurationsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, AGENT_CONFIGURATIONS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AgentConfigurationsPath : AgentConfigurations, Path<AgentConfigurationsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AgentConfigurationsRecord>?, parentPath: InverseForeignKey<out Record, AgentConfigurationsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AgentConfigurationsRecord>): super(alias, aliased)
        override fun `as`(alias: String): AgentConfigurationsPath = AgentConfigurationsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AgentConfigurationsPath = AgentConfigurationsPath(alias, this)
        override fun `as`(alias: Table<*>): AgentConfigurationsPath = AgentConfigurationsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(AGENT_CONFIGURATIONS_AGENT_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<AgentConfigurationsRecord> = AGENT_CONFIGURATIONS_PKEY
    override fun getReferences(): List<ForeignKey<AgentConfigurationsRecord, *>> = listOf(AGENT_CONFIGURATIONS__AGENT_CONFIGURATIONS_AGENT_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.agents</code> table.
     */
    fun agents(): AgentsPath = agents
    val agents: AgentsPath by lazy { AgentsPath(this, AGENT_CONFIGURATIONS__AGENT_CONFIGURATIONS_AGENT_ID_FKEY, null) }

    private lateinit var _chats: ChatsPath

    /**
     * Get the implicit to-many join path to the <code>public.chats</code> table
     */
    fun chats(): ChatsPath {
        if (!this::_chats.isInitialized)
            _chats = ChatsPath(this, null, CHATS__CHATS_AGENT_CONFIGURATION_ID_FKEY.inverseKey)

        return _chats;
    }

    val chats: ChatsPath
        get(): ChatsPath = chats()
    override fun `as`(alias: String): AgentConfigurations = AgentConfigurations(DSL.name(alias), this)
    override fun `as`(alias: Name): AgentConfigurations = AgentConfigurations(alias, this)
    override fun `as`(alias: Table<*>): AgentConfigurations = AgentConfigurations(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AgentConfigurations = AgentConfigurations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AgentConfigurations = AgentConfigurations(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AgentConfigurations = AgentConfigurations(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AgentConfigurations = AgentConfigurations(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AgentConfigurations = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AgentConfigurations = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AgentConfigurations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AgentConfigurations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AgentConfigurations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AgentConfigurations = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AgentConfigurations = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AgentConfigurations = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AgentConfigurations = where(DSL.notExists(select))
}
