@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.jirakira.indexes


import net.barrage.llmao.jirakira.tables.JirakiraWorkflows

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val JIRAKIRA_WORKFLOWS_USER_ID_IDX: Index = Internal.createIndex(DSL.name("jirakira_workflows_user_id_idx"), JirakiraWorkflows.JIRAKIRA_WORKFLOWS, arrayOf(JirakiraWorkflows.JIRAKIRA_WORKFLOWS.USER_ID), false)
