/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.bonvoyage.tables.records


import java.time.LocalDate
import java.time.OffsetDateTime
import java.time.OffsetTime
import java.util.UUID

import net.barrage.llmao.bonvoyage.tables.BonvoyageTrips

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BonvoyageTripsRecord private constructor() : UpdatableRecordImpl<BonvoyageTripsRecord>(BonvoyageTrips.BONVOYAGE_TRIPS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var travelOrderId: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var userId: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var userFullName: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var userEmail: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open var startLocation: String
        set(value): Unit = set(5, value)
        get(): String = get(5) as String

    open var stops: String
        set(value): Unit = set(6, value)
        get(): String = get(6) as String

    open var endLocation: String
        set(value): Unit = set(7, value)
        get(): String = get(7) as String

    open var transportType: String
        set(value): Unit = set(8, value)
        get(): String = get(8) as String

    open var description: String
        set(value): Unit = set(9, value)
        get(): String = get(9) as String

    open var startDate: LocalDate
        set(value): Unit = set(10, value)
        get(): LocalDate = get(10) as LocalDate

    open var endDate: LocalDate
        set(value): Unit = set(11, value)
        get(): LocalDate = get(11) as LocalDate

    open var startReminderTime: OffsetTime?
        set(value): Unit = set(12, value)
        get(): OffsetTime? = get(12) as OffsetTime?

    open var endReminderTime: OffsetTime?
        set(value): Unit = set(13, value)
        get(): OffsetTime? = get(13) as OffsetTime?

    open var startReminderSentAt: OffsetDateTime?
        set(value): Unit = set(14, value)
        get(): OffsetDateTime? = get(14) as OffsetDateTime?

    open var endReminderSentAt: OffsetDateTime?
        set(value): Unit = set(15, value)
        get(): OffsetDateTime? = get(15) as OffsetDateTime?

    open var startTime: OffsetTime?
        set(value): Unit = set(16, value)
        get(): OffsetTime? = get(16) as OffsetTime?

    open var endTime: OffsetTime?
        set(value): Unit = set(17, value)
        get(): OffsetTime? = get(17) as OffsetTime?

    open var versionSent: Int?
        set(value): Unit = set(18, value)
        get(): Int? = get(18) as Int?

    open var version: Int?
        set(value): Unit = set(19, value)
        get(): Int? = get(19) as Int?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(20, value)
        get(): OffsetDateTime? = get(20) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(21, value)
        get(): OffsetDateTime? = get(21) as OffsetDateTime?

    open var createdById: String
        set(value): Unit = set(22, value)
        get(): String = get(22) as String

    open var createdByUsername: String
        set(value): Unit = set(23, value)
        get(): String = get(23) as String

    open var createdByEmail: String
        set(value): Unit = set(24, value)
        get(): String = get(24) as String

    open var vehicleType: String?
        set(value): Unit = set(25, value)
        get(): String? = get(25) as String?

    open var vehicleRegistration: String?
        set(value): Unit = set(26, value)
        get(): String? = get(26) as String?

    open var startMileage: String?
        set(value): Unit = set(27, value)
        get(): String? = get(27) as String?

    open var endMileage: String?
        set(value): Unit = set(28, value)
        get(): String? = get(28) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDriver")
    open var isDriver: Boolean?
        set(value): Unit = set(29, value)
        get(): Boolean? = get(29) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised BonvoyageTripsRecord
     */
    constructor(id: UUID? = null, travelOrderId: String, userId: String, userFullName: String, userEmail: String, startLocation: String, stops: String, endLocation: String, transportType: String, description: String, startDate: LocalDate, endDate: LocalDate, startReminderTime: OffsetTime? = null, endReminderTime: OffsetTime? = null, startReminderSentAt: OffsetDateTime? = null, endReminderSentAt: OffsetDateTime? = null, startTime: OffsetTime? = null, endTime: OffsetTime? = null, versionSent: Int? = null, version: Int? = null, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null, createdById: String, createdByUsername: String, createdByEmail: String, vehicleType: String? = null, vehicleRegistration: String? = null, startMileage: String? = null, endMileage: String? = null, isDriver: Boolean? = null): this() {
        this.id = id
        this.travelOrderId = travelOrderId
        this.userId = userId
        this.userFullName = userFullName
        this.userEmail = userEmail
        this.startLocation = startLocation
        this.stops = stops
        this.endLocation = endLocation
        this.transportType = transportType
        this.description = description
        this.startDate = startDate
        this.endDate = endDate
        this.startReminderTime = startReminderTime
        this.endReminderTime = endReminderTime
        this.startReminderSentAt = startReminderSentAt
        this.endReminderSentAt = endReminderSentAt
        this.startTime = startTime
        this.endTime = endTime
        this.versionSent = versionSent
        this.version = version
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        this.createdById = createdById
        this.createdByUsername = createdByUsername
        this.createdByEmail = createdByEmail
        this.vehicleType = vehicleType
        this.vehicleRegistration = vehicleRegistration
        this.startMileage = startMileage
        this.endMileage = endMileage
        this.isDriver = isDriver
        resetTouchedOnNotNull()
    }
}
