/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.bonvoyage.tables.records

import java.util.UUID
import net.barrage.llmao.bonvoyage.tables.BonvoyageTripWelcomeMessages
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

/** This class is generated by jOOQ. */
@Suppress("warnings")
open class BonvoyageTripWelcomeMessagesRecord private constructor() :
  UpdatableRecordImpl<BonvoyageTripWelcomeMessagesRecord>(
    BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES
  ) {

  open var id: UUID?
    set(value): Unit = set(0, value)
    get(): UUID? = get(0) as UUID?

  open var tripId: UUID
    set(value): Unit = set(1, value)
    get(): UUID = get(1) as UUID

  open var content: String
    set(value): Unit = set(2, value)
    get(): String = get(2) as String

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

  /** Create a detached, initialised BonvoyageTripWelcomeMessagesRecord */
  constructor(id: UUID? = null, tripId: UUID, content: String) : this() {
    this.id = id
    this.tripId = tripId
    this.content = content
    resetTouchedOnNotNull()
  }
}
