/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.bonvoyage.tables.records

import java.time.OffsetDateTime
import java.util.UUID
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelExpenses
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

/** This class is generated by jOOQ. */
@Suppress("warnings")
open class BonvoyageTravelExpensesRecord private constructor() :
  UpdatableRecordImpl<BonvoyageTravelExpensesRecord>(
    BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES
  ) {

  open var id: UUID?
    set(value): Unit = set(0, value)
    get(): UUID? = get(0) as UUID?

  open var tripId: UUID
    set(value): Unit = set(1, value)
    get(): UUID = get(1) as UUID

  open var messageGroupId: UUID
    set(value): Unit = set(2, value)
    get(): UUID = get(2) as UUID

  open var amount: Double
    set(value): Unit = set(3, value)
    get(): Double = get(3) as Double

  open var currency: String
    set(value): Unit = set(4, value)
    get(): String = get(4) as String

  open var imagePath: String
    set(value): Unit = set(5, value)
    get(): String = get(5) as String

  open var imageProvider: String
    set(value): Unit = set(6, value)
    get(): String = get(6) as String

  open var description: String
    set(value): Unit = set(7, value)
    get(): String = get(7) as String

  open var expenseCreatedAt: OffsetDateTime
    set(value): Unit = set(8, value)
    get(): OffsetDateTime = get(8) as OffsetDateTime

  open var createdAt: OffsetDateTime?
    set(value): Unit = set(9, value)
    get(): OffsetDateTime? = get(9) as OffsetDateTime?

  open var updatedAt: OffsetDateTime?
    set(value): Unit = set(10, value)
    get(): OffsetDateTime? = get(10) as OffsetDateTime?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

  /** Create a detached, initialised BonvoyageTravelExpensesRecord */
  constructor(
    id: UUID? = null,
    tripId: UUID,
    messageGroupId: UUID,
    amount: Double,
    currency: String,
    imagePath: String,
    imageProvider: String,
    description: String,
    expenseCreatedAt: OffsetDateTime,
    createdAt: OffsetDateTime? = null,
    updatedAt: OffsetDateTime? = null,
  ) : this() {
    this.id = id
    this.tripId = tripId
    this.messageGroupId = messageGroupId
    this.amount = amount
    this.currency = currency
    this.imagePath = imagePath
    this.imageProvider = imageProvider
    this.description = description
    this.expenseCreatedAt = expenseCreatedAt
    this.createdAt = createdAt
    this.updatedAt = updatedAt
    resetTouchedOnNotNull()
  }
}
