/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.core.tables.records


import java.time.OffsetDateTime

import net.barrage.llmao.core.tables.ApplicationSettings

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ApplicationSettingsRecord private constructor() : UpdatableRecordImpl<ApplicationSettingsRecord>(ApplicationSettings.APPLICATION_SETTINGS) {

    open var name: String
        set(value): Unit = set(0, value)
        get(): String = get(0) as String

    open var value: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ApplicationSettingsRecord
     */
    constructor(name: String, value: String, createdAt: OffsetDateTime? = null, updatedAt: OffsetDateTime? = null): this() {
        this.name = name
        this.value = value
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
