/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.core.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import net.barrage.llmao.core.tables.MessageGroups

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class MessageGroupsRecord private constructor() : UpdatableRecordImpl<MessageGroupsRecord>(MessageGroups.MESSAGE_GROUPS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var parentId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var parentType: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised MessageGroupsRecord
     */
    constructor(id: UUID? = null, parentId: UUID, parentType: String, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.parentId = parentId
        this.parentType = parentType
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }
}
