/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.core.tables.records


import java.time.OffsetDateTime
import java.util.UUID

import net.barrage.llmao.core.tables.Messages

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class MessagesRecord private constructor() : UpdatableRecordImpl<MessagesRecord>(Messages.MESSAGES) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var messageGroupId: UUID
        set(value): Unit = set(1, value)
        get(): UUID = get(1) as UUID

    open var order: Int
        set(value): Unit = set(2, value)
        get(): Int = get(2) as Int

    open var senderType: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var content: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var finishReason: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var toolCalls: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var toolCallId: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised MessagesRecord
     */
    constructor(id: UUID? = null, messageGroupId: UUID, order: Int, senderType: String, content: String? = null, finishReason: String? = null, toolCalls: String? = null, toolCallId: String? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.messageGroupId = messageGroupId
        this.order = order
        this.senderType = senderType
        this.content = content
        this.finishReason = finishReason
        this.toolCalls = toolCalls
        this.toolCallId = toolCallId
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }
}
