/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.core.tables.records


import java.util.UUID

import net.barrage.llmao.core.tables.MessageAttachments

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class MessageAttachmentsRecord private constructor() : UpdatableRecordImpl<MessageAttachmentsRecord>(MessageAttachments.MESSAGE_ATTACHMENTS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var type: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var provider: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var order: Int
        set(value): Unit = set(3, value)
        get(): Int = get(3) as Int

    open var url: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open var messageId: UUID
        set(value): Unit = set(5, value)
        get(): UUID = get(5) as UUID

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised MessageAttachmentsRecord
     */
    constructor(id: UUID? = null, type: String, provider: String? = null, order: Int, url: String, messageId: UUID): this() {
        this.id = id
        this.type = type
        this.provider = provider
        this.order = order
        this.url = url
        this.messageId = messageId
        resetTouchedOnNotNull()
    }
}
