@file:Suppress("warnings")

/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.jirakira.tables.references

import net.barrage.llmao.jirakira.tables.JiraApiKeys
import net.barrage.llmao.jirakira.tables.JiraWorklogAttributes
import net.barrage.llmao.jirakira.tables.JirakiraWorkflows

/** The table <code>public.jira_api_keys</code>. */
val JIRA_API_KEYS: JiraApiKeys = JiraApiKeys.JIRA_API_KEYS

/** The table <code>public.jira_worklog_attributes</code>. */
val JIRA_WORKLOG_ATTRIBUTES: JiraWorklogAttributes = JiraWorklogAttributes.JIRA_WORKLOG_ATTRIBUTES

/** The table <code>public.jirakira_workflows</code>. */
val JIRAKIRA_WORKFLOWS: JirakiraWorkflows = JirakiraWorkflows.JIRAKIRA_WORKFLOWS
