/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.bonvoyage.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import net.barrage.llmao.bonvoyage.Public
import net.barrage.llmao.bonvoyage.indexes.BONVOYAGE_TRIP_WELCOME_MESSAGES_TRIP_ID_IDX
import net.barrage.llmao.bonvoyage.keys.BONVOYAGE_TRIP_WELCOME_MESSAGES_PKEY
import net.barrage.llmao.bonvoyage.keys.BONVOYAGE_TRIP_WELCOME_MESSAGES__BONVOYAGE_TRIP_WELCOME_MESSAGES_TRIP_ID_FKEY
import net.barrage.llmao.bonvoyage.tables.BonvoyageTrips.BonvoyageTripsPath
import net.barrage.llmao.bonvoyage.tables.records.BonvoyageTripWelcomeMessagesRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BonvoyageTripWelcomeMessages(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BonvoyageTripWelcomeMessagesRecord>?,
    parentPath: InverseForeignKey<out Record, BonvoyageTripWelcomeMessagesRecord>?,
    aliased: Table<BonvoyageTripWelcomeMessagesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BonvoyageTripWelcomeMessagesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.bonvoyage_trip_welcome_messages</code>
         */
        val BONVOYAGE_TRIP_WELCOME_MESSAGES: BonvoyageTripWelcomeMessages = BonvoyageTripWelcomeMessages()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BonvoyageTripWelcomeMessagesRecord> = BonvoyageTripWelcomeMessagesRecord::class.java

    /**
     * The column <code>public.bonvoyage_trip_welcome_messages.id</code>.
     */
    val ID: TableField<BonvoyageTripWelcomeMessagesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.bonvoyage_trip_welcome_messages.trip_id</code>.
     */
    val TRIP_ID: TableField<BonvoyageTripWelcomeMessagesRecord, UUID?> = createField(DSL.name("trip_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.bonvoyage_trip_welcome_messages.content</code>.
     */
    val CONTENT: TableField<BonvoyageTripWelcomeMessagesRecord, String?> = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<BonvoyageTripWelcomeMessagesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BonvoyageTripWelcomeMessagesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BonvoyageTripWelcomeMessagesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.bonvoyage_trip_welcome_messages</code>
     * table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.bonvoyage_trip_welcome_messages</code>
     * table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.bonvoyage_trip_welcome_messages</code> table
     * reference
     */
    constructor(): this(DSL.name("bonvoyage_trip_welcome_messages"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BonvoyageTripWelcomeMessagesRecord>?, parentPath: InverseForeignKey<out Record, BonvoyageTripWelcomeMessagesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, BONVOYAGE_TRIP_WELCOME_MESSAGES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class BonvoyageTripWelcomeMessagesPath : BonvoyageTripWelcomeMessages, Path<BonvoyageTripWelcomeMessagesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BonvoyageTripWelcomeMessagesRecord>?, parentPath: InverseForeignKey<out Record, BonvoyageTripWelcomeMessagesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<BonvoyageTripWelcomeMessagesRecord>): super(alias, aliased)
        override fun `as`(alias: String): BonvoyageTripWelcomeMessagesPath = BonvoyageTripWelcomeMessagesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): BonvoyageTripWelcomeMessagesPath = BonvoyageTripWelcomeMessagesPath(alias, this)
        override fun `as`(alias: Table<*>): BonvoyageTripWelcomeMessagesPath = BonvoyageTripWelcomeMessagesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(BONVOYAGE_TRIP_WELCOME_MESSAGES_TRIP_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<BonvoyageTripWelcomeMessagesRecord> = BONVOYAGE_TRIP_WELCOME_MESSAGES_PKEY
    override fun getReferences(): List<ForeignKey<BonvoyageTripWelcomeMessagesRecord, *>> = listOf(BONVOYAGE_TRIP_WELCOME_MESSAGES__BONVOYAGE_TRIP_WELCOME_MESSAGES_TRIP_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.bonvoyage_trips</code>
     * table.
     */
    fun bonvoyageTrips(): BonvoyageTripsPath = bonvoyageTrips
    val bonvoyageTrips: BonvoyageTripsPath by lazy { BonvoyageTripsPath(this, BONVOYAGE_TRIP_WELCOME_MESSAGES__BONVOYAGE_TRIP_WELCOME_MESSAGES_TRIP_ID_FKEY, null) }
    override fun `as`(alias: String): BonvoyageTripWelcomeMessages = BonvoyageTripWelcomeMessages(DSL.name(alias), this)
    override fun `as`(alias: Name): BonvoyageTripWelcomeMessages = BonvoyageTripWelcomeMessages(alias, this)
    override fun `as`(alias: Table<*>): BonvoyageTripWelcomeMessages = BonvoyageTripWelcomeMessages(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BonvoyageTripWelcomeMessages = BonvoyageTripWelcomeMessages(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BonvoyageTripWelcomeMessages = BonvoyageTripWelcomeMessages(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BonvoyageTripWelcomeMessages = BonvoyageTripWelcomeMessages(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): BonvoyageTripWelcomeMessages = BonvoyageTripWelcomeMessages(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): BonvoyageTripWelcomeMessages = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): BonvoyageTripWelcomeMessages = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): BonvoyageTripWelcomeMessages = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): BonvoyageTripWelcomeMessages = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): BonvoyageTripWelcomeMessages = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): BonvoyageTripWelcomeMessages = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): BonvoyageTripWelcomeMessages = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): BonvoyageTripWelcomeMessages = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): BonvoyageTripWelcomeMessages = where(DSL.notExists(select))
}
