/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.bonvoyage.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import net.barrage.llmao.bonvoyage.Public
import net.barrage.llmao.bonvoyage.indexes.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_TRAVEL_MANAGER_ID_IDX
import net.barrage.llmao.bonvoyage.indexes.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_USER_ID_IDX
import net.barrage.llmao.bonvoyage.keys.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_PKEY
import net.barrage.llmao.bonvoyage.keys.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS__BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_TRAVEL_MANAGER_ID_FKEY
import net.barrage.llmao.bonvoyage.keys.UNIQUE_TRAVEL_MANAGER_USER_MAPPING
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelManagers.BonvoyageTravelManagersPath
import net.barrage.llmao.bonvoyage.tables.records.BonvoyageTravelManagerUserMappingsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BonvoyageTravelManagerUserMappings(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, BonvoyageTravelManagerUserMappingsRecord>?,
    parentPath: InverseForeignKey<out Record, BonvoyageTravelManagerUserMappingsRecord>?,
    aliased: Table<BonvoyageTravelManagerUserMappingsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<BonvoyageTravelManagerUserMappingsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.bonvoyage_travel_manager_user_mappings</code>
         */
        val BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS: BonvoyageTravelManagerUserMappings = BonvoyageTravelManagerUserMappings()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<BonvoyageTravelManagerUserMappingsRecord> = BonvoyageTravelManagerUserMappingsRecord::class.java

    /**
     * The column <code>public.bonvoyage_travel_manager_user_mappings.id</code>.
     */
    val ID: TableField<BonvoyageTravelManagerUserMappingsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "")

    /**
     * The column
     * <code>public.bonvoyage_travel_manager_user_mappings.travel_manager_id</code>.
     */
    val TRAVEL_MANAGER_ID: TableField<BonvoyageTravelManagerUserMappingsRecord, String?> = createField(DSL.name("travel_manager_id"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>public.bonvoyage_travel_manager_user_mappings.user_id</code>.
     */
    val USER_ID: TableField<BonvoyageTravelManagerUserMappingsRecord, String?> = createField(DSL.name("user_id"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>public.bonvoyage_travel_manager_user_mappings.delivery</code>.
     */
    val DELIVERY: TableField<BonvoyageTravelManagerUserMappingsRecord, String?> = createField(DSL.name("delivery"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column
     * <code>public.bonvoyage_travel_manager_user_mappings.created_at</code>.
     */
    val CREATED_AT: TableField<BonvoyageTravelManagerUserMappingsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<BonvoyageTravelManagerUserMappingsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<BonvoyageTravelManagerUserMappingsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<BonvoyageTravelManagerUserMappingsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased
     * <code>public.bonvoyage_travel_manager_user_mappings</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased
     * <code>public.bonvoyage_travel_manager_user_mappings</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.bonvoyage_travel_manager_user_mappings</code> table
     * reference
     */
    constructor(): this(DSL.name("bonvoyage_travel_manager_user_mappings"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BonvoyageTravelManagerUserMappingsRecord>?, parentPath: InverseForeignKey<out Record, BonvoyageTravelManagerUserMappingsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class BonvoyageTravelManagerUserMappingsPath : BonvoyageTravelManagerUserMappings, Path<BonvoyageTravelManagerUserMappingsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, BonvoyageTravelManagerUserMappingsRecord>?, parentPath: InverseForeignKey<out Record, BonvoyageTravelManagerUserMappingsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<BonvoyageTravelManagerUserMappingsRecord>): super(alias, aliased)
        override fun `as`(alias: String): BonvoyageTravelManagerUserMappingsPath = BonvoyageTravelManagerUserMappingsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): BonvoyageTravelManagerUserMappingsPath = BonvoyageTravelManagerUserMappingsPath(alias, this)
        override fun `as`(alias: Table<*>): BonvoyageTravelManagerUserMappingsPath = BonvoyageTravelManagerUserMappingsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_TRAVEL_MANAGER_ID_IDX, BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_USER_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<BonvoyageTravelManagerUserMappingsRecord> = BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<BonvoyageTravelManagerUserMappingsRecord>> = listOf(UNIQUE_TRAVEL_MANAGER_USER_MAPPING)
    override fun getReferences(): List<ForeignKey<BonvoyageTravelManagerUserMappingsRecord, *>> = listOf(BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS__BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_TRAVEL_MANAGER_ID_FKEY)

    /**
     * Get the implicit join path to the
     * <code>public.bonvoyage_travel_managers</code> table.
     */
    fun bonvoyageTravelManagers(): BonvoyageTravelManagersPath = bonvoyageTravelManagers
    val bonvoyageTravelManagers: BonvoyageTravelManagersPath by lazy { BonvoyageTravelManagersPath(this, BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS__BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_TRAVEL_MANAGER_ID_FKEY, null) }
    override fun `as`(alias: String): BonvoyageTravelManagerUserMappings = BonvoyageTravelManagerUserMappings(DSL.name(alias), this)
    override fun `as`(alias: Name): BonvoyageTravelManagerUserMappings = BonvoyageTravelManagerUserMappings(alias, this)
    override fun `as`(alias: Table<*>): BonvoyageTravelManagerUserMappings = BonvoyageTravelManagerUserMappings(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): BonvoyageTravelManagerUserMappings = BonvoyageTravelManagerUserMappings(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): BonvoyageTravelManagerUserMappings = BonvoyageTravelManagerUserMappings(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): BonvoyageTravelManagerUserMappings = BonvoyageTravelManagerUserMappings(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): BonvoyageTravelManagerUserMappings = BonvoyageTravelManagerUserMappings(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): BonvoyageTravelManagerUserMappings = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): BonvoyageTravelManagerUserMappings = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): BonvoyageTravelManagerUserMappings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): BonvoyageTravelManagerUserMappings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): BonvoyageTravelManagerUserMappings = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): BonvoyageTravelManagerUserMappings = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): BonvoyageTravelManagerUserMappings = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): BonvoyageTravelManagerUserMappings = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): BonvoyageTravelManagerUserMappings = where(DSL.notExists(select))
}
