/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.chat.tables.records

import java.util.UUID
import net.barrage.llmao.chat.tables.AgentTools
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

/** This class is generated by jOOQ. */
@Suppress("warnings")
open class AgentToolsRecord private constructor() :
  UpdatableRecordImpl<AgentToolsRecord>(AgentTools.AGENT_TOOLS) {

  open var id: UUID?
    set(value): Unit = set(0, value)
    get(): UUID? = get(0) as UUID?

  open var agentId: UUID
    set(value): Unit = set(1, value)
    get(): UUID = get(1) as UUID

  open var toolName: String
    set(value): Unit = set(2, value)
    get(): String = get(2) as String

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

  /** Create a detached, initialised AgentToolsRecord */
  constructor(id: UUID? = null, agentId: UUID, toolName: String) : this() {
    this.id = id
    this.agentId = agentId
    this.toolName = toolName
    resetTouchedOnNotNull()
  }
}
