/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.chat.tables.records

import java.time.OffsetDateTime
import java.util.UUID
import net.barrage.llmao.chat.tables.Agents
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

/** This class is generated by jOOQ. */
@Suppress("warnings")
open class AgentsRecord private constructor() : UpdatableRecordImpl<AgentsRecord>(Agents.AGENTS) {

  open var id: UUID?
    set(value): Unit = set(0, value)
    get(): UUID? = get(0) as UUID?

  open var name: String
    set(value): Unit = set(1, value)
    get(): String = get(1) as String

  open var description: String?
    set(value): Unit = set(2, value)
    get(): String? = get(2) as String?

  open var active: Boolean
    set(value): Unit = set(3, value)
    get(): Boolean = get(3) as Boolean

  open var activeConfigurationId: UUID?
    set(value): Unit = set(4, value)
    get(): UUID? = get(4) as UUID?

  open var language: String?
    set(value): Unit = set(5, value)
    get(): String? = get(5) as String?

  open var avatar: String?
    set(value): Unit = set(6, value)
    get(): String? = get(6) as String?

  open var createdAt: OffsetDateTime?
    set(value): Unit = set(7, value)
    get(): OffsetDateTime? = get(7) as OffsetDateTime?

  open var updatedAt: OffsetDateTime?
    set(value): Unit = set(8, value)
    get(): OffsetDateTime? = get(8) as OffsetDateTime?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

  /** Create a detached, initialised AgentsRecord */
  constructor(
    id: UUID? = null,
    name: String,
    description: String? = null,
    active: Boolean,
    activeConfigurationId: UUID? = null,
    language: String? = null,
    avatar: String? = null,
    createdAt: OffsetDateTime? = null,
    updatedAt: OffsetDateTime? = null,
  ) : this() {
    this.id = id
    this.name = name
    this.description = description
    this.active = active
    this.activeConfigurationId = activeConfigurationId
    this.language = language
    this.avatar = avatar
    this.createdAt = createdAt
    this.updatedAt = updatedAt
    resetTouchedOnNotNull()
  }
}
