/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.bonvoyage

import kotlin.collections.List
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelExpenses
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelManagerUserMappings
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelManagers
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelRequests
import net.barrage.llmao.bonvoyage.tables.BonvoyageTripWelcomeMessages
import net.barrage.llmao.bonvoyage.tables.BonvoyageTrips
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl

/** standard public schema */
@Suppress("warnings")
open class Public :
  SchemaImpl(
    DSL.name("public"),
    DefaultCatalog.DEFAULT_CATALOG,
    DSL.comment("standard public schema"),
  ) {
  companion object {

    /** The reference instance of <code>public</code> */
    val PUBLIC: Public = Public()
  }

  /** The table <code>public.bonvoyage_travel_expenses</code>. */
  val BONVOYAGE_TRAVEL_EXPENSES: BonvoyageTravelExpenses
    get() = BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES

  /** The table <code>public.bonvoyage_travel_manager_user_mappings</code>. */
  val BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS: BonvoyageTravelManagerUserMappings
    get() = BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS

  /** The table <code>public.bonvoyage_travel_managers</code>. */
  val BONVOYAGE_TRAVEL_MANAGERS: BonvoyageTravelManagers
    get() = BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS

  /** The table <code>public.bonvoyage_travel_requests</code>. */
  val BONVOYAGE_TRAVEL_REQUESTS: BonvoyageTravelRequests
    get() = BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS

  /** The table <code>public.bonvoyage_trip_welcome_messages</code>. */
  val BONVOYAGE_TRIP_WELCOME_MESSAGES: BonvoyageTripWelcomeMessages
    get() = BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES

  /** The table <code>public.bonvoyage_trips</code>. */
  val BONVOYAGE_TRIPS: BonvoyageTrips
    get() = BonvoyageTrips.BONVOYAGE_TRIPS

  override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

  override fun getTables(): List<Table<*>> =
    listOf(
      BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES,
      BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS,
      BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS,
      BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS,
      BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES,
      BonvoyageTrips.BONVOYAGE_TRIPS,
    )
}
