@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.chat.indexes


import net.barrage.llmao.chat.tables.AgentCollections
import net.barrage.llmao.chat.tables.AgentConfigurations
import net.barrage.llmao.chat.tables.AgentPermissions
import net.barrage.llmao.chat.tables.AgentTools
import net.barrage.llmao.chat.tables.Agents
import net.barrage.llmao.chat.tables.Chats
import net.barrage.llmao.chat.tables.WhatsAppNumbers

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val AGENT_COLLECTIONS_AGENT_ID_IDX: Index = Internal.createIndex(DSL.name("agent_collections_agent_id_idx"), AgentCollections.AGENT_COLLECTIONS, arrayOf(AgentCollections.AGENT_COLLECTIONS.AGENT_ID), false)
val AGENT_CONFIGURATIONS_AGENT_ID_IDX: Index = Internal.createIndex(DSL.name("agent_configurations_agent_id_idx"), AgentConfigurations.AGENT_CONFIGURATIONS, arrayOf(AgentConfigurations.AGENT_CONFIGURATIONS.AGENT_ID), false)
val AGENT_PERMISSIONS_AGENT_ID_IDX: Index = Internal.createIndex(DSL.name("agent_permissions_agent_id_idx"), AgentPermissions.AGENT_PERMISSIONS, arrayOf(AgentPermissions.AGENT_PERMISSIONS.AGENT_ID), false)
val AGENT_TOOLS_AGENT_ID_IDX: Index = Internal.createIndex(DSL.name("agent_tools_agent_id_idx"), AgentTools.AGENT_TOOLS, arrayOf(AgentTools.AGENT_TOOLS.AGENT_ID), false)
val AGENTS_ACTIVE_IDX: Index = Internal.createIndex(DSL.name("agents_active_idx"), Agents.AGENTS, arrayOf(Agents.AGENTS.ACTIVE), false)
val CHATS_AGENT_ID_IDX: Index = Internal.createIndex(DSL.name("chats_agent_id_idx"), Chats.CHATS, arrayOf(Chats.CHATS.AGENT_ID), false)
val CHATS_TYPE_IDX: Index = Internal.createIndex(DSL.name("chats_type_idx"), Chats.CHATS, arrayOf(Chats.CHATS.TYPE), false)
val CHATS_USER_ID_IDX: Index = Internal.createIndex(DSL.name("chats_user_id_idx"), Chats.CHATS, arrayOf(Chats.CHATS.USER_ID), false)
val IDX_WHATSAPP_NUMBERS_PHONE_NUMBER: Index = Internal.createIndex(DSL.name("idx_whatsapp_numbers_phone_number"), WhatsAppNumbers.WHATS_APP_NUMBERS, arrayOf(WhatsAppNumbers.WHATS_APP_NUMBERS.PHONE_NUMBER), false)
val IDX_WHATSAPP_NUMBERS_USER_ID: Index = Internal.createIndex(DSL.name("idx_whatsapp_numbers_user_id"), WhatsAppNumbers.WHATS_APP_NUMBERS, arrayOf(WhatsAppNumbers.WHATS_APP_NUMBERS.USER_ID), false)
