@file:Suppress("warnings")

/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.jirakira.keys

import net.barrage.llmao.jirakira.tables.JiraWorklogAttributes
import net.barrage.llmao.jirakira.tables.JirakiraWorkflows
import net.barrage.llmao.jirakira.tables.records.JiraWorklogAttributesRecord
import net.barrage.llmao.jirakira.tables.records.JirakiraWorkflowsRecord
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal

// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val JIRA_WORKLOG_ATTRIBUTES_ID_KEY: UniqueKey<JiraWorklogAttributesRecord> =
  Internal.createUniqueKey(
    JiraWorklogAttributes.JIRA_WORKLOG_ATTRIBUTES,
    DSL.name("jira_worklog_attributes_id_key"),
    arrayOf(JiraWorklogAttributes.JIRA_WORKLOG_ATTRIBUTES.ID),
    true,
  )
val JIRAKIRA_WORKFLOWS_PKEY: UniqueKey<JirakiraWorkflowsRecord> =
  Internal.createUniqueKey(
    JirakiraWorkflows.JIRAKIRA_WORKFLOWS,
    DSL.name("jirakira_workflows_pkey"),
    arrayOf(JirakiraWorkflows.JIRAKIRA_WORKFLOWS.ID),
    true,
  )
