/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.jirakira.tables

import java.time.OffsetDateTime
import java.util.UUID
import kotlin.collections.Collection
import kotlin.collections.List
import net.barrage.llmao.jirakira.Public
import net.barrage.llmao.jirakira.indexes.JIRAKIRA_WORKFLOWS_USER_ID_IDX
import net.barrage.llmao.jirakira.keys.JIRAKIRA_WORKFLOWS_PKEY
import net.barrage.llmao.jirakira.tables.records.JirakiraWorkflowsRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/** This class is generated by jOOQ. */
@Suppress("warnings")
open class JirakiraWorkflows(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, JirakiraWorkflowsRecord>?,
  parentPath: InverseForeignKey<out Record, JirakiraWorkflowsRecord>?,
  aliased: Table<JirakiraWorkflowsRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?,
) :
  TableImpl<JirakiraWorkflowsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
  ) {
  companion object {

    /** The reference instance of <code>public.jirakira_workflows</code> */
    val JIRAKIRA_WORKFLOWS: JirakiraWorkflows = JirakiraWorkflows()
  }

  /** The class holding records for this type */
  override fun getRecordType(): Class<JirakiraWorkflowsRecord> = JirakiraWorkflowsRecord::class.java

  /** The column <code>public.jirakira_workflows.id</code>. */
  val ID: TableField<JirakiraWorkflowsRecord, UUID?> =
    createField(
      DSL.name("id"),
      SQLDataType.UUID.nullable(false)
        .defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)),
      this,
      "",
    )

  /** The column <code>public.jirakira_workflows.user_id</code>. */
  val USER_ID: TableField<JirakiraWorkflowsRecord, String?> =
    createField(DSL.name("user_id"), SQLDataType.CLOB.nullable(false), this, "")

  /** The column <code>public.jirakira_workflows.username</code>. */
  val USERNAME: TableField<JirakiraWorkflowsRecord, String?> =
    createField(DSL.name("username"), SQLDataType.CLOB, this, "")

  /** The column <code>public.jirakira_workflows.created_at</code>. */
  val CREATED_AT: TableField<JirakiraWorkflowsRecord, OffsetDateTime?> =
    createField(
      DSL.name("created_at"),
      SQLDataType.TIMESTAMPWITHTIMEZONE(6)
        .nullable(false)
        .defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
      this,
      "",
    )

  private constructor(
    alias: Name,
    aliased: Table<JirakiraWorkflowsRecord>?,
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<JirakiraWorkflowsRecord>?,
    parameters: Array<Field<*>?>?,
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<JirakiraWorkflowsRecord>?,
    where: Condition?,
  ) : this(alias, null, null, null, aliased, null, where)

  /** Create an aliased <code>public.jirakira_workflows</code> table reference */
  constructor(alias: String) : this(DSL.name(alias))

  /** Create an aliased <code>public.jirakira_workflows</code> table reference */
  constructor(alias: Name) : this(alias, null)

  /** Create a <code>public.jirakira_workflows</code> table reference */
  constructor() : this(DSL.name("jirakira_workflows"), null)

  override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC

  override fun getIndexes(): List<Index> = listOf(JIRAKIRA_WORKFLOWS_USER_ID_IDX)

  override fun getPrimaryKey(): UniqueKey<JirakiraWorkflowsRecord> = JIRAKIRA_WORKFLOWS_PKEY

  override fun `as`(alias: String): JirakiraWorkflows = JirakiraWorkflows(DSL.name(alias), this)

  override fun `as`(alias: Name): JirakiraWorkflows = JirakiraWorkflows(alias, this)

  override fun `as`(alias: Table<*>): JirakiraWorkflows =
    JirakiraWorkflows(alias.qualifiedName, this)

  /** Rename this table */
  override fun rename(name: String): JirakiraWorkflows = JirakiraWorkflows(DSL.name(name), null)

  /** Rename this table */
  override fun rename(name: Name): JirakiraWorkflows = JirakiraWorkflows(name, null)

  /** Rename this table */
  override fun rename(name: Table<*>): JirakiraWorkflows =
    JirakiraWorkflows(name.qualifiedName, null)

  /** Create an inline derived table from this table */
  override fun where(condition: Condition?): JirakiraWorkflows =
    JirakiraWorkflows(qualifiedName, if (aliased()) this else null, condition)

  /** Create an inline derived table from this table */
  override fun where(conditions: Collection<Condition>): JirakiraWorkflows =
    where(DSL.and(conditions))

  /** Create an inline derived table from this table */
  override fun where(vararg conditions: Condition?): JirakiraWorkflows = where(DSL.and(*conditions))

  /** Create an inline derived table from this table */
  override fun where(condition: Field<Boolean?>?): JirakiraWorkflows =
    where(DSL.condition(condition))

  /** Create an inline derived table from this table */
  @PlainSQL override fun where(condition: SQL): JirakiraWorkflows = where(DSL.condition(condition))

  /** Create an inline derived table from this table */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): JirakiraWorkflows =
    where(DSL.condition(condition))

  /** Create an inline derived table from this table */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JirakiraWorkflows =
    where(DSL.condition(condition, *binds))

  /** Create an inline derived table from this table */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JirakiraWorkflows =
    where(DSL.condition(condition, *parts))

  /** Create an inline derived table from this table */
  override fun whereExists(select: Select<*>): JirakiraWorkflows = where(DSL.exists(select))

  /** Create an inline derived table from this table */
  override fun whereNotExists(select: Select<*>): JirakiraWorkflows = where(DSL.notExists(select))
}
