/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.jirakira.tables

import kotlin.collections.Collection
import net.barrage.llmao.jirakira.Public
import net.barrage.llmao.jirakira.tables.records.JiraApiKeysRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/** This class is generated by jOOQ. */
@Suppress("warnings")
open class JiraApiKeys(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, JiraApiKeysRecord>?,
  parentPath: InverseForeignKey<out Record, JiraApiKeysRecord>?,
  aliased: Table<JiraApiKeysRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?,
) :
  TableImpl<JiraApiKeysRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
  ) {
  companion object {

    /** The reference instance of <code>public.jira_api_keys</code> */
    val JIRA_API_KEYS: JiraApiKeys = JiraApiKeys()
  }

  /** The class holding records for this type */
  override fun getRecordType(): Class<JiraApiKeysRecord> = JiraApiKeysRecord::class.java

  /** The column <code>public.jira_api_keys.user_id</code>. */
  val USER_ID: TableField<JiraApiKeysRecord, String?> =
    createField(DSL.name("user_id"), SQLDataType.CLOB.nullable(false), this, "")

  /** The column <code>public.jira_api_keys.api_key</code>. */
  val API_KEY: TableField<JiraApiKeysRecord, String?> =
    createField(DSL.name("api_key"), SQLDataType.CLOB.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<JiraApiKeysRecord>?,
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<JiraApiKeysRecord>?,
    parameters: Array<Field<*>?>?,
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<JiraApiKeysRecord>?,
    where: Condition?,
  ) : this(alias, null, null, null, aliased, null, where)

  /** Create an aliased <code>public.jira_api_keys</code> table reference */
  constructor(alias: String) : this(DSL.name(alias))

  /** Create an aliased <code>public.jira_api_keys</code> table reference */
  constructor(alias: Name) : this(alias, null)

  /** Create a <code>public.jira_api_keys</code> table reference */
  constructor() : this(DSL.name("jira_api_keys"), null)

  override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC

  override fun `as`(alias: String): JiraApiKeys = JiraApiKeys(DSL.name(alias), this)

  override fun `as`(alias: Name): JiraApiKeys = JiraApiKeys(alias, this)

  override fun `as`(alias: Table<*>): JiraApiKeys = JiraApiKeys(alias.qualifiedName, this)

  /** Rename this table */
  override fun rename(name: String): JiraApiKeys = JiraApiKeys(DSL.name(name), null)

  /** Rename this table */
  override fun rename(name: Name): JiraApiKeys = JiraApiKeys(name, null)

  /** Rename this table */
  override fun rename(name: Table<*>): JiraApiKeys = JiraApiKeys(name.qualifiedName, null)

  /** Create an inline derived table from this table */
  override fun where(condition: Condition?): JiraApiKeys =
    JiraApiKeys(qualifiedName, if (aliased()) this else null, condition)

  /** Create an inline derived table from this table */
  override fun where(conditions: Collection<Condition>): JiraApiKeys = where(DSL.and(conditions))

  /** Create an inline derived table from this table */
  override fun where(vararg conditions: Condition?): JiraApiKeys = where(DSL.and(*conditions))

  /** Create an inline derived table from this table */
  override fun where(condition: Field<Boolean?>?): JiraApiKeys = where(DSL.condition(condition))

  /** Create an inline derived table from this table */
  @PlainSQL override fun where(condition: SQL): JiraApiKeys = where(DSL.condition(condition))

  /** Create an inline derived table from this table */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): JiraApiKeys = where(DSL.condition(condition))

  /** Create an inline derived table from this table */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JiraApiKeys =
    where(DSL.condition(condition, *binds))

  /** Create an inline derived table from this table */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JiraApiKeys =
    where(DSL.condition(condition, *parts))

  /** Create an inline derived table from this table */
  override fun whereExists(select: Select<*>): JiraApiKeys = where(DSL.exists(select))

  /** Create an inline derived table from this table */
  override fun whereNotExists(select: Select<*>): JiraApiKeys = where(DSL.notExists(select))
}
