/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.jirakira.tables


import kotlin.collections.Collection
import kotlin.collections.List

import net.barrage.llmao.jirakira.Public
import net.barrage.llmao.jirakira.keys.JIRA_WORKLOG_ATTRIBUTES_ID_KEY
import net.barrage.llmao.jirakira.tables.records.JiraWorklogAttributesRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JiraWorklogAttributes(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JiraWorklogAttributesRecord>?,
    parentPath: InverseForeignKey<out Record, JiraWorklogAttributesRecord>?,
    aliased: Table<JiraWorklogAttributesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JiraWorklogAttributesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.jira_worklog_attributes</code>
         */
        val JIRA_WORKLOG_ATTRIBUTES: JiraWorklogAttributes = JiraWorklogAttributes()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JiraWorklogAttributesRecord> = JiraWorklogAttributesRecord::class.java

    /**
     * The column <code>public.jira_worklog_attributes.id</code>.
     */
    val ID: TableField<JiraWorklogAttributesRecord, String?> = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.jira_worklog_attributes.description</code>.
     */
    val DESCRIPTION: TableField<JiraWorklogAttributesRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.jira_worklog_attributes.required</code>.
     */
    val REQUIRED: TableField<JiraWorklogAttributesRecord, Boolean?> = createField(DSL.name("required"), SQLDataType.BOOLEAN.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<JiraWorklogAttributesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JiraWorklogAttributesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JiraWorklogAttributesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.jira_worklog_attributes</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.jira_worklog_attributes</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.jira_worklog_attributes</code> table reference
     */
    constructor(): this(DSL.name("jira_worklog_attributes"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getUniqueKeys(): List<UniqueKey<JiraWorklogAttributesRecord>> = listOf(JIRA_WORKLOG_ATTRIBUTES_ID_KEY)
    override fun `as`(alias: String): JiraWorklogAttributes = JiraWorklogAttributes(DSL.name(alias), this)
    override fun `as`(alias: Name): JiraWorklogAttributes = JiraWorklogAttributes(alias, this)
    override fun `as`(alias: Table<*>): JiraWorklogAttributes = JiraWorklogAttributes(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JiraWorklogAttributes = JiraWorklogAttributes(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JiraWorklogAttributes = JiraWorklogAttributes(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JiraWorklogAttributes = JiraWorklogAttributes(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JiraWorklogAttributes = JiraWorklogAttributes(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JiraWorklogAttributes = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JiraWorklogAttributes = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JiraWorklogAttributes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JiraWorklogAttributes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JiraWorklogAttributes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JiraWorklogAttributes = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JiraWorklogAttributes = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JiraWorklogAttributes = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JiraWorklogAttributes = where(DSL.notExists(select))
}
