ingress:
  className: nginx-external
  tls:
    enabled: true
  annotations:
    # cert-manager.io/cluster-issuer: barrage-dev
    acme.cert-manager.io/http01-edit-in-place: true 
    cert-manager.io/cluster-issuer: barrage-le-production
    ingress.kubernetes.io/ssl-redirect: False
    ## The following annotation is to limit access to the ingress

barrage:
  vault:
    role: llmao-kappi-k8-dev
    moduleWorkspace: llmao/data/deploy-kappi-dev