ktor:
  application:
    modules:
      - net.barrage.llmao.ApplicationKt.module
  deployment:
    port: 42069
  environment: "development"

db:
  url: "jdbc:postgresql://localhost:5454/kappi"
  user: "postgres"
  password: "postgres"
  driver: "org.postgresql.Driver"

cors:
  origins: "http://localhost:3000 http://localhost:3001"
  methods: "GET HEAD PUT PATCH POST DELETE"
  headers: "*"
  maxAge: 3600

llm:
  provider: "azure"
  openAi:
    authorization: "Bearer YOUR_API_KEY"
  azure:
    apiVersion: "2023-05-15"
    embeddingsEndpoint: "YOUR_EMBEDDINGS_ENDPOINT"
    embeddingsKey: "YOUR_EMBEDDINGS_KEY"
    LLMEndpoint: "YOUR_LLM_ENDPOINT"
    LLMKey: "YOUR_LLM_KEY"

weaviate:
  host: "localhost:8080"
  scheme: "http"
  documentation:
    collection: "LLMAODocumentation"
    fields: "content parentDocumentId fileName fileType title section page"
    nResults: 5
#    where:
#    distanceFilter:

oauth:
  google:
    tokenEndpoint: "https://oauth2.googleapis.com/token"
    accountEndpoint: "https://openidconnect.googleapis.com/v1/userinfo"
    clientId: "clientId"
    clientSecret: "clientSecret"

session:
  cookieName: "kappi"
  httpOnly: false
  secure: false
  domain: "localhost" # ".barrage.corp" for guja

infobip:
  api_key: "apiKey"
  endpoint: "endpoint.infobip.com"