ktor:
  application:
    modules:
      - net.barrage.llmao.ApplicationKt.module
  deployment:
    port: 42069

db:
  url: "jdbc:postgresql://localhost:5454/kappi"
  user: "postgres"
  password: "postgres"
  driver: "org.postgresql.Driver"

cors:
  origins: "http://localhost:3000 http://localhost:3001"
  methods: "GET HEAD PUT PATCH POST DELETE"
  headers: "*"
  maxAge: 3600