ktor:
  application:
    modules:
      - net.barrage.llmao.ApplicationKt.module
  deployment:
    port: 42069
  environment: "development"

db:
  url: "jdbc:postgresql://localhost:5454/kappi"
  user: "postgres"
  password: "postgres"
  driver: "org.postgresql.Driver"

cors:
  origins: [ "http://localhost:3000", "http://localhost:3001" ]
  methods: [ "GET","HEAD", "PUT", "PATCH", "POST", "DELETE", "OPTIONS" ]
  headers: [ ]

llm:
  openAi:
    apiKey: "Bearer YOUR_API_KEY"
  azure:
    apiVersion: "2023-05-15"
    endpoint: "YOUR_LLM_ENDPOINT"
    apiKey: "YOUR_LLM_KEY"
  ollama:
    endpoint: ""

embeddings:
  azure:
    apiVersion: "2023-05-15"
    endpoint: "YOUR_EMBEDDINGS_ENDPOINT"
    apiKey: "YOUR_EMBEDDINGS_KEY"
  fembed:
    endpoint: ""

weaviate:
  host: "localhost:8080"
  scheme: "http"

oauth:
  google:
    tokenEndpoint: "https://oauth2.googleapis.com/token"
    accountEndpoint: "https://openidconnect.googleapis.com/v1/userinfo"
    clientId: "clientId"
    clientSecret: "clientSecret"

session:
  cookieName: "kappi"
  httpOnly: false
  secure: false
  domain: "localhost" # ".barrage.corp" for guja

infobip:
  api_key: "apiKey"
  endpoint: "endpoint.infobip.com"