ktor:
  application:
    modules:
      - net.barrage.llmao.ApplicationKt.module
  deployment:
    port: 42069
  environment: "development"

frontend:
  url: "http://localhost:3000"

db:
  url: "jdbc:postgresql://localhost:5454/kappi"
  user: "postgres"
  password: "postgres"
  driver: "org.postgresql.Driver"
  runMigrations: true

cors:
  origins: [ "http://localhost:3000", "http://localhost:3001", "https://appleid.apple.com" ]
  methods: [ "GET","HEAD", "PUT", "PATCH", "POST", "DELETE", "OPTIONS" ]
  headers: [ ]

llm:
  openai:
    endpoint: "https://api.openai.com/v1/"
    apiKey: ""
  azure:
    apiVersion: "2023-05-15"
    endpoint: ""
    apiKey: ""
  ollama:
    endpoint: ""

embeddings:
  openai:
    endpoint: "https://api.openai.com/v1/"
    apiKey: ""
  azure:
    endpoint: "https://YOUR_RESOURCE.openai.azure.com/openai/deployments"
    deployment: "gipitty-text-embedding-ada-002"
    apiVersion: "2023-05-15"
    apiKey: "YOUR_EMBEDDINGS_KEY"
  fembed:
    endpoint: ""

weaviate:
  host: "localhost:8080"
  scheme: "http"

oauth:
  google:
    tokenEndpoint: "https://oauth2.googleapis.com/token"
    accountEndpoint: "https://openidconnect.googleapis.com/v1/userinfo"
    clientId: "clientId"
    clientSecret: "clientSecret"
  apple:
    endpoint: "https://appleid.apple.com"
    clientId: ""
    serviceId: ""
    clientSecret: ""
    keyId: ""
    teamId: ""

session:
  cookieName: "kappi"
  httpOnly: false
  secure: false
  domain: "localhost" # ".barrage.corp" for guja
  sameSite: "Lax"

infobip:
  apiKey: "apiKey"
  endpoint: "endpoint.infobip.com"

apple:
  appID: "appID"

android:
  namespace: "namespace"
  packageName: "packageName"
  sha256CertFingerprints:
    - "sha256CertFingerprint"

multiplatform:
  ios:
    appID: "appID"
