/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.jirakira.tables.records

import net.barrage.llmao.jirakira.tables.JiraApiKeys
import org.jooq.impl.TableRecordImpl

/** This class is generated by jOOQ. */
@Suppress("warnings")
open class JiraApiKeysRecord private constructor() :
  TableRecordImpl<JiraApiKeysRecord>(JiraApiKeys.JIRA_API_KEYS) {

  open var userId: String
    set(value): Unit = set(0, value)
    get(): String = get(0) as String

  open var apiKey: String
    set(value): Unit = set(1, value)
    get(): String = get(1) as String

  /** Create a detached, initialised JiraApiKeysRecord */
  constructor(userId: String, apiKey: String) : this() {
    this.userId = userId
    this.apiKey = apiKey
    resetTouchedOnNotNull()
  }
}
