/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.jirakira.tables.records

import net.barrage.llmao.jirakira.tables.JiraWorklogAttributes
import org.jooq.impl.TableRecordImpl

/** This class is generated by jOOQ. */
@Suppress("warnings")
open class JiraWorklogAttributesRecord private constructor() :
  TableRecordImpl<JiraWorklogAttributesRecord>(JiraWorklogAttributes.JIRA_WORKLOG_ATTRIBUTES) {

  open var id: String
    set(value): Unit = set(0, value)
    get(): String = get(0) as String

  open var description: String
    set(value): Unit = set(1, value)
    get(): String = get(1) as String

  open var required: Boolean
    set(value): Unit = set(2, value)
    get(): Boolean = get(2) as Boolean

  /** Create a detached, initialised JiraWorklogAttributesRecord */
  constructor(id: String, description: String, required: Boolean) : this() {
    this.id = id
    this.description = description
    this.required = required
    resetTouchedOnNotNull()
  }
}
