@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.bonvoyage.keys


import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelExpenses
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelManagerUserMappings
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelManagers
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelRequests
import net.barrage.llmao.bonvoyage.tables.BonvoyageTripWelcomeMessages
import net.barrage.llmao.bonvoyage.tables.BonvoyageTrips
import net.barrage.llmao.bonvoyage.tables.records.BonvoyageTravelExpensesRecord
import net.barrage.llmao.bonvoyage.tables.records.BonvoyageTravelManagerUserMappingsRecord
import net.barrage.llmao.bonvoyage.tables.records.BonvoyageTravelManagersRecord
import net.barrage.llmao.bonvoyage.tables.records.BonvoyageTravelRequestsRecord
import net.barrage.llmao.bonvoyage.tables.records.BonvoyageTripWelcomeMessagesRecord
import net.barrage.llmao.bonvoyage.tables.records.BonvoyageTripsRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val BONVOYAGE_TRAVEL_EXPENSES_PKEY: UniqueKey<BonvoyageTravelExpensesRecord> = Internal.createUniqueKey(BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES, DSL.name("bonvoyage_travel_expenses_pkey"), arrayOf(BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES.ID), true)
val BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_PKEY: UniqueKey<BonvoyageTravelManagerUserMappingsRecord> = Internal.createUniqueKey(BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS, DSL.name("bonvoyage_travel_manager_user_mappings_pkey"), arrayOf(BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS.ID), true)
val UNIQUE_TRAVEL_MANAGER_USER_MAPPING: UniqueKey<BonvoyageTravelManagerUserMappingsRecord> = Internal.createUniqueKey(BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS, DSL.name("unique_travel_manager_user_mapping"), arrayOf(BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS.TRAVEL_MANAGER_ID, BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS.USER_ID, BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS.DELIVERY), true)
val BONVOYAGE_TRAVEL_MANAGERS_PKEY: UniqueKey<BonvoyageTravelManagersRecord> = Internal.createUniqueKey(BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS, DSL.name("bonvoyage_travel_managers_pkey"), arrayOf(BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS.USER_ID), true)
val BONVOYAGE_TRAVEL_REQUESTS_PKEY: UniqueKey<BonvoyageTravelRequestsRecord> = Internal.createUniqueKey(BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS, DSL.name("bonvoyage_travel_requests_pkey"), arrayOf(BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS.ID), true)
val BONVOYAGE_TRIP_WELCOME_MESSAGES_PKEY: UniqueKey<BonvoyageTripWelcomeMessagesRecord> = Internal.createUniqueKey(BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES, DSL.name("bonvoyage_trip_welcome_messages_pkey"), arrayOf(BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES.ID), true)
val BONVOYAGE_TRIPS_PKEY: UniqueKey<BonvoyageTripsRecord> = Internal.createUniqueKey(BonvoyageTrips.BONVOYAGE_TRIPS, DSL.name("bonvoyage_trips_pkey"), arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val BONVOYAGE_TRAVEL_EXPENSES__BONVOYAGE_TRAVEL_EXPENSES_TRIP_ID_FKEY: ForeignKey<BonvoyageTravelExpensesRecord, BonvoyageTripsRecord> = Internal.createForeignKey(BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES, DSL.name("bonvoyage_travel_expenses_trip_id_fkey"), arrayOf(BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES.TRIP_ID), net.barrage.llmao.bonvoyage.keys.BONVOYAGE_TRIPS_PKEY, arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS__BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_TRAVEL_MANAGER_ID_FKEY: ForeignKey<BonvoyageTravelManagerUserMappingsRecord, BonvoyageTravelManagersRecord> = Internal.createForeignKey(BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS, DSL.name("bonvoyage_travel_manager_user_mappings_travel_manager_id_fkey"), arrayOf(BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS.TRAVEL_MANAGER_ID), net.barrage.llmao.bonvoyage.keys.BONVOYAGE_TRAVEL_MANAGERS_PKEY, arrayOf(BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS.USER_ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val BONVOYAGE_TRAVEL_REQUESTS__BONVOYAGE_TRAVEL_REQUESTS_TRIP_ID_FKEY: ForeignKey<BonvoyageTravelRequestsRecord, BonvoyageTripsRecord> = Internal.createForeignKey(BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS, DSL.name("bonvoyage_travel_requests_trip_id_fkey"), arrayOf(BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS.TRIP_ID), net.barrage.llmao.bonvoyage.keys.BONVOYAGE_TRIPS_PKEY, arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.ID), true, ForeignKeyRule.SET_NULL, ForeignKeyRule.NO_ACTION)
val BONVOYAGE_TRIP_WELCOME_MESSAGES__BONVOYAGE_TRIP_WELCOME_MESSAGES_TRIP_ID_FKEY: ForeignKey<BonvoyageTripWelcomeMessagesRecord, BonvoyageTripsRecord> = Internal.createForeignKey(BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES, DSL.name("bonvoyage_trip_welcome_messages_trip_id_fkey"), arrayOf(BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES.TRIP_ID), net.barrage.llmao.bonvoyage.keys.BONVOYAGE_TRIPS_PKEY, arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
