@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.core.keys


import net.barrage.llmao.core.tables.ApplicationSettings
import net.barrage.llmao.core.tables.MessageAttachments
import net.barrage.llmao.core.tables.MessageGroupEvaluations
import net.barrage.llmao.core.tables.MessageGroups
import net.barrage.llmao.core.tables.Messages
import net.barrage.llmao.core.tables.TokenUsage
import net.barrage.llmao.core.tables.records.ApplicationSettingsRecord
import net.barrage.llmao.core.tables.records.MessageAttachmentsRecord
import net.barrage.llmao.core.tables.records.MessageGroupEvaluationsRecord
import net.barrage.llmao.core.tables.records.MessageGroupsRecord
import net.barrage.llmao.core.tables.records.MessagesRecord
import net.barrage.llmao.core.tables.records.TokenUsageRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val APPLICATION_SETTINGS_PKEY: UniqueKey<ApplicationSettingsRecord> = Internal.createUniqueKey(ApplicationSettings.APPLICATION_SETTINGS, DSL.name("application_settings_pkey"), arrayOf(ApplicationSettings.APPLICATION_SETTINGS.NAME), true)
val MESSAGE_ATTACHMENTS_PKEY: UniqueKey<MessageAttachmentsRecord> = Internal.createUniqueKey(MessageAttachments.MESSAGE_ATTACHMENTS, DSL.name("message_attachments_pkey"), arrayOf(MessageAttachments.MESSAGE_ATTACHMENTS.ID), true)
val MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_KEY: UniqueKey<MessageGroupEvaluationsRecord> = Internal.createUniqueKey(MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS, DSL.name("message_group_evaluations_message_group_id_key"), arrayOf(MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS.MESSAGE_GROUP_ID), true)
val MESSAGE_GROUP_EVALUATIONS_PKEY: UniqueKey<MessageGroupEvaluationsRecord> = Internal.createUniqueKey(MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS, DSL.name("message_group_evaluations_pkey"), arrayOf(MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS.ID), true)
val MESSAGE_GROUPS_PKEY: UniqueKey<MessageGroupsRecord> = Internal.createUniqueKey(MessageGroups.MESSAGE_GROUPS, DSL.name("message_groups_pkey"), arrayOf(MessageGroups.MESSAGE_GROUPS.ID), true)
val MESSAGES_PKEY: UniqueKey<MessagesRecord> = Internal.createUniqueKey(Messages.MESSAGES, DSL.name("messages_pkey"), arrayOf(Messages.MESSAGES.ID), true)
val TOKEN_USAGE_PKEY: UniqueKey<TokenUsageRecord> = Internal.createUniqueKey(TokenUsage.TOKEN_USAGE, DSL.name("token_usage_pkey"), arrayOf(TokenUsage.TOKEN_USAGE.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val MESSAGE_ATTACHMENTS__MESSAGE_ATTACHMENTS_MESSAGE_ID_FKEY: ForeignKey<MessageAttachmentsRecord, MessagesRecord> = Internal.createForeignKey(MessageAttachments.MESSAGE_ATTACHMENTS, DSL.name("message_attachments_message_id_fkey"), arrayOf(MessageAttachments.MESSAGE_ATTACHMENTS.MESSAGE_ID), net.barrage.llmao.core.keys.MESSAGES_PKEY, arrayOf(Messages.MESSAGES.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val MESSAGE_GROUP_EVALUATIONS__MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_FKEY: ForeignKey<MessageGroupEvaluationsRecord, MessageGroupsRecord> = Internal.createForeignKey(MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS, DSL.name("message_group_evaluations_message_group_id_fkey"), arrayOf(MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS.MESSAGE_GROUP_ID), net.barrage.llmao.core.keys.MESSAGE_GROUPS_PKEY, arrayOf(MessageGroups.MESSAGE_GROUPS.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val MESSAGES__MESSAGES_MESSAGE_GROUP_ID_FKEY: ForeignKey<MessagesRecord, MessageGroupsRecord> = Internal.createForeignKey(Messages.MESSAGES, DSL.name("messages_message_group_id_fkey"), arrayOf(Messages.MESSAGES.MESSAGE_GROUP_ID), net.barrage.llmao.core.keys.MESSAGE_GROUPS_PKEY, arrayOf(MessageGroups.MESSAGE_GROUPS.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
