CREATE TABLE llm_configs (
    id UUID PRIMARY KEY UNIQUE DEFAULT uuid_generate_v4(),
    chat_id UUID NOT NULL,
    model VARCHAR(255) NOT NULL,
    streaming BOOLEAN NOT NULL DEFAULT TRUE,
    temperature FLOAT NOT NULL DEFAULT 0.1,
    language VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);