@file:Suppress("warnings")

/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.bonvoyage.indexes

import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelExpenses
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelManagerUserMappings
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelManagers
import net.barrage.llmao.bonvoyage.tables.BonvoyageTravelRequests
import net.barrage.llmao.bonvoyage.tables.BonvoyageTripWelcomeMessages
import net.barrage.llmao.bonvoyage.tables.BonvoyageTrips
import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal

// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val BONVOYAGE_TRAVEL_EXPENSES_CREATED_AT_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_expenses_created_at_idx"),
    BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES,
    arrayOf(BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES.CREATED_AT),
    false,
  )
val BONVOYAGE_TRAVEL_EXPENSES_EXPENSE_CREATED_AT_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_expenses_expense_created_at_idx"),
    BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES,
    arrayOf(BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES.EXPENSE_CREATED_AT),
    false,
  )
val BONVOYAGE_TRAVEL_EXPENSES_TRIP_ID_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_expenses_trip_id_idx"),
    BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES,
    arrayOf(BonvoyageTravelExpenses.BONVOYAGE_TRAVEL_EXPENSES.TRIP_ID),
    false,
  )
val BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_TRAVEL_MANAGER_ID_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_manager_user_mappings_travel_manager_id_idx"),
    BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS,
    arrayOf(
      BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS.TRAVEL_MANAGER_ID
    ),
    false,
  )
val BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS_USER_ID_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_manager_user_mappings_user_id_idx"),
    BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS,
    arrayOf(BonvoyageTravelManagerUserMappings.BONVOYAGE_TRAVEL_MANAGER_USER_MAPPINGS.USER_ID),
    false,
  )
val BONVOYAGE_TRAVEL_MANAGERS_USER_EMAIL_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_managers_user_email_idx"),
    BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS,
    arrayOf(BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS.USER_EMAIL),
    false,
  )
val BONVOYAGE_TRAVEL_MANAGERS_USER_ID_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_managers_user_id_idx"),
    BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS,
    arrayOf(BonvoyageTravelManagers.BONVOYAGE_TRAVEL_MANAGERS.USER_ID),
    false,
  )
val BONVOYAGE_TRAVEL_REQUESTS_STATUS_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_requests_status_idx"),
    BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS,
    arrayOf(BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS.STATUS),
    false,
  )
val BONVOYAGE_TRAVEL_REQUESTS_TRIP_ID_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_requests_trip_id_idx"),
    BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS,
    arrayOf(BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS.TRIP_ID),
    false,
  )
val BONVOYAGE_TRAVEL_REQUESTS_USER_ID_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_travel_requests_user_id_idx"),
    BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS,
    arrayOf(BonvoyageTravelRequests.BONVOYAGE_TRAVEL_REQUESTS.USER_ID),
    false,
  )
val BONVOYAGE_TRIP_WELCOME_MESSAGES_TRIP_ID_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_trip_welcome_messages_trip_id_idx"),
    BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES,
    arrayOf(BonvoyageTripWelcomeMessages.BONVOYAGE_TRIP_WELCOME_MESSAGES.TRIP_ID),
    false,
  )
val BONVOYAGE_TRIPS_END_DATE_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_trips_end_date_idx"),
    BonvoyageTrips.BONVOYAGE_TRIPS,
    arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.END_DATE),
    false,
  )
val BONVOYAGE_TRIPS_END_REMINDER_SENT_AT_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_trips_end_reminder_sent_at_idx"),
    BonvoyageTrips.BONVOYAGE_TRIPS,
    arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.END_REMINDER_SENT_AT),
    false,
  )
val BONVOYAGE_TRIPS_START_DATE_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_trips_start_date_idx"),
    BonvoyageTrips.BONVOYAGE_TRIPS,
    arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.START_DATE),
    false,
  )
val BONVOYAGE_TRIPS_START_REMINDER_SENT_AT_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_trips_start_reminder_sent_at_idx"),
    BonvoyageTrips.BONVOYAGE_TRIPS,
    arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.START_REMINDER_SENT_AT),
    false,
  )
val BONVOYAGE_TRIPS_TRAVEL_ORDER_ID_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_trips_travel_order_id_idx"),
    BonvoyageTrips.BONVOYAGE_TRIPS,
    arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.TRAVEL_ORDER_ID),
    false,
  )
val BONVOYAGE_TRIPS_USER_ID_IDX: Index =
  Internal.createIndex(
    DSL.name("bonvoyage_trips_user_id_idx"),
    BonvoyageTrips.BONVOYAGE_TRIPS,
    arrayOf(BonvoyageTrips.BONVOYAGE_TRIPS.USER_ID),
    false,
  )
