/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.core.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import net.barrage.llmao.core.Public
import net.barrage.llmao.core.indexes.MESSAGE_ATTACHMENTS_MESSAGE_ID_IDX
import net.barrage.llmao.core.keys.MESSAGE_ATTACHMENTS_PKEY
import net.barrage.llmao.core.keys.MESSAGE_ATTACHMENTS__MESSAGE_ATTACHMENTS_MESSAGE_ID_FKEY
import net.barrage.llmao.core.tables.Messages.MessagesPath
import net.barrage.llmao.core.tables.records.MessageAttachmentsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class MessageAttachments(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MessageAttachmentsRecord>?,
    parentPath: InverseForeignKey<out Record, MessageAttachmentsRecord>?,
    aliased: Table<MessageAttachmentsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<MessageAttachmentsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.message_attachments</code>
         */
        val MESSAGE_ATTACHMENTS: MessageAttachments = MessageAttachments()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MessageAttachmentsRecord> = MessageAttachmentsRecord::class.java

    /**
     * The column <code>public.message_attachments.id</code>.
     */
    val ID: TableField<MessageAttachmentsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.message_attachments.type</code>.
     */
    val TYPE: TableField<MessageAttachmentsRecord, String?> = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.message_attachments.provider</code>.
     */
    val PROVIDER: TableField<MessageAttachmentsRecord, String?> = createField(DSL.name("provider"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.message_attachments.order</code>.
     */
    val ORDER: TableField<MessageAttachmentsRecord, Int?> = createField(DSL.name("order"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.message_attachments.url</code>.
     */
    val URL: TableField<MessageAttachmentsRecord, String?> = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.message_attachments.message_id</code>.
     */
    val MESSAGE_ID: TableField<MessageAttachmentsRecord, UUID?> = createField(DSL.name("message_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<MessageAttachmentsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<MessageAttachmentsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<MessageAttachmentsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.message_attachments</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.message_attachments</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.message_attachments</code> table reference
     */
    constructor(): this(DSL.name("message_attachments"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MessageAttachmentsRecord>?, parentPath: InverseForeignKey<out Record, MessageAttachmentsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, MESSAGE_ATTACHMENTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class MessageAttachmentsPath : MessageAttachments, Path<MessageAttachmentsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MessageAttachmentsRecord>?, parentPath: InverseForeignKey<out Record, MessageAttachmentsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<MessageAttachmentsRecord>): super(alias, aliased)
        override fun `as`(alias: String): MessageAttachmentsPath = MessageAttachmentsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): MessageAttachmentsPath = MessageAttachmentsPath(alias, this)
        override fun `as`(alias: Table<*>): MessageAttachmentsPath = MessageAttachmentsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(MESSAGE_ATTACHMENTS_MESSAGE_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<MessageAttachmentsRecord> = MESSAGE_ATTACHMENTS_PKEY
    override fun getReferences(): List<ForeignKey<MessageAttachmentsRecord, *>> = listOf(MESSAGE_ATTACHMENTS__MESSAGE_ATTACHMENTS_MESSAGE_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.messages</code> table.
     */
    fun messages(): MessagesPath = messages
    val messages: MessagesPath by lazy { MessagesPath(this, MESSAGE_ATTACHMENTS__MESSAGE_ATTACHMENTS_MESSAGE_ID_FKEY, null) }
    override fun `as`(alias: String): MessageAttachments = MessageAttachments(DSL.name(alias), this)
    override fun `as`(alias: Name): MessageAttachments = MessageAttachments(alias, this)
    override fun `as`(alias: Table<*>): MessageAttachments = MessageAttachments(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): MessageAttachments = MessageAttachments(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): MessageAttachments = MessageAttachments(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): MessageAttachments = MessageAttachments(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): MessageAttachments = MessageAttachments(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): MessageAttachments = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): MessageAttachments = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): MessageAttachments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): MessageAttachments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): MessageAttachments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): MessageAttachments = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): MessageAttachments = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): MessageAttachments = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): MessageAttachments = where(DSL.notExists(select))
}
