/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.core.tables


import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import net.barrage.llmao.core.Public
import net.barrage.llmao.core.indexes.MESSAGE_GROUP_EVALUATIONS_EVALUATION_IDX
import net.barrage.llmao.core.indexes.MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_IDX
import net.barrage.llmao.core.keys.MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_KEY
import net.barrage.llmao.core.keys.MESSAGE_GROUP_EVALUATIONS_PKEY
import net.barrage.llmao.core.keys.MESSAGE_GROUP_EVALUATIONS__MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_FKEY
import net.barrage.llmao.core.tables.MessageGroups.MessageGroupsPath
import net.barrage.llmao.core.tables.records.MessageGroupEvaluationsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class MessageGroupEvaluations(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, MessageGroupEvaluationsRecord>?,
    parentPath: InverseForeignKey<out Record, MessageGroupEvaluationsRecord>?,
    aliased: Table<MessageGroupEvaluationsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<MessageGroupEvaluationsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>public.message_group_evaluations</code>
         */
        val MESSAGE_GROUP_EVALUATIONS: MessageGroupEvaluations = MessageGroupEvaluations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<MessageGroupEvaluationsRecord> = MessageGroupEvaluationsRecord::class.java

    /**
     * The column <code>public.message_group_evaluations.id</code>.
     */
    val ID: TableField<MessageGroupEvaluationsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "")

    /**
     * The column
     * <code>public.message_group_evaluations.message_group_id</code>.
     */
    val MESSAGE_GROUP_ID: TableField<MessageGroupEvaluationsRecord, UUID?> = createField(DSL.name("message_group_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.message_group_evaluations.evaluation</code>.
     */
    val EVALUATION: TableField<MessageGroupEvaluationsRecord, Boolean?> = createField(DSL.name("evaluation"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.message_group_evaluations.feedback</code>.
     */
    val FEEDBACK: TableField<MessageGroupEvaluationsRecord, String?> = createField(DSL.name("feedback"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.message_group_evaluations.created_at</code>.
     */
    val CREATED_AT: TableField<MessageGroupEvaluationsRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.message_group_evaluations.updated_at</code>.
     */
    val UPDATED_AT: TableField<MessageGroupEvaluationsRecord, OffsetDateTime?> = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    private constructor(alias: Name, aliased: Table<MessageGroupEvaluationsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<MessageGroupEvaluationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<MessageGroupEvaluationsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.message_group_evaluations</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.message_group_evaluations</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.message_group_evaluations</code> table reference
     */
    constructor(): this(DSL.name("message_group_evaluations"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MessageGroupEvaluationsRecord>?, parentPath: InverseForeignKey<out Record, MessageGroupEvaluationsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, MESSAGE_GROUP_EVALUATIONS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class MessageGroupEvaluationsPath : MessageGroupEvaluations, Path<MessageGroupEvaluationsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, MessageGroupEvaluationsRecord>?, parentPath: InverseForeignKey<out Record, MessageGroupEvaluationsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<MessageGroupEvaluationsRecord>): super(alias, aliased)
        override fun `as`(alias: String): MessageGroupEvaluationsPath = MessageGroupEvaluationsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): MessageGroupEvaluationsPath = MessageGroupEvaluationsPath(alias, this)
        override fun `as`(alias: Table<*>): MessageGroupEvaluationsPath = MessageGroupEvaluationsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(MESSAGE_GROUP_EVALUATIONS_EVALUATION_IDX, MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_IDX)
    override fun getPrimaryKey(): UniqueKey<MessageGroupEvaluationsRecord> = MESSAGE_GROUP_EVALUATIONS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<MessageGroupEvaluationsRecord>> = listOf(MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_KEY)
    override fun getReferences(): List<ForeignKey<MessageGroupEvaluationsRecord, *>> = listOf(MESSAGE_GROUP_EVALUATIONS__MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.message_groups</code>
     * table.
     */
    fun messageGroups(): MessageGroupsPath = messageGroups
    val messageGroups: MessageGroupsPath by lazy { MessageGroupsPath(this, MESSAGE_GROUP_EVALUATIONS__MESSAGE_GROUP_EVALUATIONS_MESSAGE_GROUP_ID_FKEY, null) }
    override fun `as`(alias: String): MessageGroupEvaluations = MessageGroupEvaluations(DSL.name(alias), this)
    override fun `as`(alias: Name): MessageGroupEvaluations = MessageGroupEvaluations(alias, this)
    override fun `as`(alias: Table<*>): MessageGroupEvaluations = MessageGroupEvaluations(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): MessageGroupEvaluations = MessageGroupEvaluations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): MessageGroupEvaluations = MessageGroupEvaluations(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): MessageGroupEvaluations = MessageGroupEvaluations(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): MessageGroupEvaluations = MessageGroupEvaluations(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): MessageGroupEvaluations = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): MessageGroupEvaluations = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): MessageGroupEvaluations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): MessageGroupEvaluations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): MessageGroupEvaluations = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): MessageGroupEvaluations = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): MessageGroupEvaluations = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): MessageGroupEvaluations = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): MessageGroupEvaluations = where(DSL.notExists(select))
}
