@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.barrage.llmao.core.tables.references


import net.barrage.llmao.core.tables.ApplicationSettings
import net.barrage.llmao.core.tables.MessageAttachments
import net.barrage.llmao.core.tables.MessageGroupEvaluations
import net.barrage.llmao.core.tables.MessageGroups
import net.barrage.llmao.core.tables.Messages
import net.barrage.llmao.core.tables.TokenUsage



/**
 * The table <code>public.application_settings</code>.
 */
val APPLICATION_SETTINGS: ApplicationSettings = ApplicationSettings.APPLICATION_SETTINGS

/**
 * The table <code>public.message_attachments</code>.
 */
val MESSAGE_ATTACHMENTS: MessageAttachments = MessageAttachments.MESSAGE_ATTACHMENTS

/**
 * The table <code>public.message_group_evaluations</code>.
 */
val MESSAGE_GROUP_EVALUATIONS: MessageGroupEvaluations = MessageGroupEvaluations.MESSAGE_GROUP_EVALUATIONS

/**
 * The table <code>public.message_groups</code>.
 */
val MESSAGE_GROUPS: MessageGroups = MessageGroups.MESSAGE_GROUPS

/**
 * The table <code>public.messages</code>.
 */
val MESSAGES: Messages = Messages.MESSAGES

/**
 * The table <code>public.token_usage</code>.
 */
val TOKEN_USAGE: TokenUsage = TokenUsage.TOKEN_USAGE
